const POKEMON = {
  1: { name: "Bulbasaur", gen: 1, forms: ["mega"] },
  2: { name: "Ivysaur", gen: 1 },
  3: { name: "Venusaur", gen: 1, forms: ["mega", "gmax"] },
  4: { name: "Charmander", gen: 1 },
  5: { name: "Charmeleon", gen: 1 },
  6: { name: "Charizard", gen: 1, forms: ["mega", "gmax"] },
  7: { name: "Squirtle", gen: 1 },
  8: { name: "Wartortle", gen: 1 },
  9: { name: "Blastoise", gen: 1, forms: ["mega", "gmax"] },
  10: { name: "Caterpie", gen: 1 },
  11: { name: "Metapod", gen: 1 },
  12: { name: "Butterfree", gen: 1, forms: ["gmax"] },
  13: { name: "Weedle", gen: 1 },
  14: { name: "Kakuna", gen: 1 },
  15: { name: "Beedrill", gen: 1, forms: ["mega"] },
  16: { name: "Pidgey", gen: 1 },
  17: { name: "Pidgeotto", gen: 1 },
  18: { name: "Pidgeot", gen: 1, forms: ["mega"] },
  19: { name: "Rattata", gen: 1, forms: ["alola"] },
  20: { name: "Raticate", gen: 1, forms: ["alola"] },
  21: { name: "Spearow", gen: 1 },
  22: { name: "Fearow", gen: 1 },
  23: { name: "Ekans", gen: 1 },
  24: { name: "Arbok", gen: 1 },
  25: { name: "Pikachu", gen: 1, forms: ["gmax"] },
  26: { name: "Raichu", gen: 1, forms: ["alola"] },
  27: { name: "Sandshrew", gen: 1, forms: ["alola"] },
  28: { name: "Sandslash", gen: 1, forms: ["alola"] },
  29: { name: "Nidoran♀", gen: 1 },
  30: { name: "Nidorina", gen: 1 },
  31: { name: "Nidoqueen", gen: 1 },
  32: { name: "Nidoran♂", gen: 1 },
  33: { name: "Nidorino", gen: 1 },
  34: { name: "Nidoking", gen: 1 },
  35: { name: "Clefairy", gen: 1 },
  36: { name: "Clefable", gen: 1 },
  37: { name: "Vulpix", gen: 1, forms: ["alola"] },
  38: { name: "Ninetales", gen: 1, forms: ["alola"] },
  39: { name: "Jigglypuff", gen: 1 },
  40: { name: "Wigglytuff", gen: 1 },
  41: { name: "Zubat", gen: 1 },
  42: { name: "Golbat", gen: 1 },
  43: { name: "Oddish", gen: 1 },
  44: { name: "Gloom", gen: 1 },
  45: { name: "Vileplume", gen: 1 },
  46: { name: "Paras", gen: 1 },
  47: { name: "Parasect", gen: 1 },
  48: { name: "Venonat", gen: 1 },
  49: { name: "Venomoth", gen: 1 },
  50: { name: "Diglett", gen: 1, forms: ["alola"] },
  51: { name: "Dugtrio", gen: 1, forms: ["alola"] },
  52: { name: "Meowth", gen: 1, forms: ["alola", "galar", "gmax"] },
  53: { name: "Persian", gen: 1, forms: ["alola"] },
  54: { name: "Psyduck", gen: 1 },
  55: { name: "Golduck", gen: 1 },
  56: { name: "Mankey", gen: 1 },
  57: { name: "Primeape", gen: 1 },
  58: { name: "Growlithe", gen: 1, forms: ["hisui"] },
  59: { name: "Arcanine", gen: 1, forms: ["hisui"] },
  60: { name: "Poliwag", gen: 1 },
  61: { name: "Poliwhirl", gen: 1 },
  62: { name: "Poliwrath", gen: 1 },
  63: { name: "Abra", gen: 1 },
  64: { name: "Kadabra", gen: 1 },
  65: { name: "Alakazam", gen: 1, forms: ["mega"] },
  66: { name: "Machop", gen: 1 },
  67: { name: "Machoke", gen: 1 },
  68: { name: "Machamp", gen: 1, forms: ["gmax"] },
  69: { name: "Bellsprout", gen: 1 },
  70: { name: "Weepinbell", gen: 1 },
  71: { name: "Victreebel", gen: 1 },
  72: { name: "Tentacool", gen: 1 },
  73: { name: "Tentacruel", gen: 1 },
  74: { name: "Geodude", gen: 1, forms: ["alola"] },
  75: { name: "Graveler", gen: 1, forms: ["alola"] },
  76: { name: "Golem", gen: 1, forms: ["alola"] },
  77: { name: "Ponyta", gen: 1, forms: ["galar"] },
  78: { name: "Rapidash", gen: 1, forms: ["galar"] },
  79: { name: "Slowpoke", gen: 1, forms: ["galar"] },
  80: { name: "Slowbro", gen: 1, forms: ["mega", "galar"] },
  81: { name: "Magnemite", gen: 1 },
  82: { name: "Magneton", gen: 1 },
  83: { name: "Farfetch'd", gen: 1, forms: ["galar"] },
  84: { name: "Doduo", gen: 1 },
  85: { name: "Dodrio", gen: 1 },
  86: { name: "Seel", gen: 1 },
  87: { name: "Dewgong", gen: 1 },
  88: { name: "Grimer", gen: 1, forms: ["alola"] },
  89: { name: "Muk", gen: 1, forms: ["alola"] },
  90: { name: "Shellder", gen: 1 },
  91: { name: "Cloyster", gen: 1 },
  92: { name: "Gastly", gen: 1 },
  93: { name: "Haunter", gen: 1 },
  94: { name: "Gengar", gen: 1, forms: ["mega", "gmax"] },
  95: { name: "Onix", gen: 1 },
  96: { name: "Drowzee", gen: 1 },
  97: { name: "Hypno", gen: 1 },
  98: { name: "Krabby", gen: 1 },
  99: { name: "Kingler", gen: 1, forms: ["gmax"] },
  100: { name: "Voltorb", gen: 1, forms: ["hisui"] },
  101: { name: "Electrode", gen: 1, forms: ["hisui"] },
  102: { name: "Exeggcute", gen: 1 },
  103: { name: "Exeggutor", gen: 1, forms: ["alola"] },
  104: { name: "Cubone", gen: 1 },
  105: { name: "Marowak", gen: 1, forms: ["alola"] },
  106: { name: "Hitmonlee", gen: 1 },
  107: { name: "Hitmonchan", gen: 1 },
  108: { name: "Lickitung", gen: 1 },
  109: { name: "Koffing", gen: 1, forms: ["galar"] },
  110: { name: "Weezing", gen: 1, forms: ["galar"] },
  111: { name: "Rhyhorn", gen: 1 },
  112: { name: "Rhydon", gen: 1 },
  113: { name: "Chansey", gen: 1 },
  114: { name: "Tangela", gen: 1 },
  115: { name: "Kangaskhan", gen: 1, forms: ["mega"] },
  116: { name: "Horsea", gen: 1 },
  117: { name: "Seadra", gen: 1 },
  118: { name: "Goldeen", gen: 1 },
  119: { name: "Seaking", gen: 1 },
  120: { name: "Staryu", gen: 1 },
  121: { name: "Starmie", gen: 1 },
  122: { name: "Mr. Mime", gen: 1, forms: ["galar"] },
  123: { name: "Scyther", gen: 1 },
  124: { name: "Jynx", gen: 1 },
  125: { name: "Electabuzz", gen: 1 },
  126: { name: "Magmar", gen: 1 },
  127: { name: "Pinsir", gen: 1, forms: ["mega"] },
  128: { name: "Tauros", gen: 1, forms: ["paldea"] },
  129: { name: "Magikarp", gen: 1 },
  130: { name: "Gyarados", gen: 1, forms: ["mega"] },
  131: { name: "Lapras", gen: 1, forms: ["gmax"] },
  132: { name: "Ditto", gen: 1 },
  133: { name: "Eevee", gen: 1, forms: ["gmax"] },
  134: { name: "Vaporeon", gen: 1 },
  135: { name: "Jolteon", gen: 1 },
  136: { name: "Flareon", gen: 1 },
  137: { name: "Porygon", gen: 1 },
  138: { name: "Omanyte", gen: 1 },
  139: { name: "Omastar", gen: 1 },
  140: { name: "Kabuto", gen: 1 },
  141: { name: "Kabutops", gen: 1 },
  142: { name: "Aerodactyl", gen: 1, forms: ["mega"] },
  143: { name: "Snorlax", gen: 1, forms: ["gmax"] },
  144: { name: "Articuno", gen: 1, forms: ["galar"] },
  145: { name: "Zapdos", gen: 1, forms: ["galar"] },
  146: { name: "Moltres", gen: 1, forms: ["galar"] },
  147: { name: "Dratini", gen: 1 },
  148: { name: "Dragonair", gen: 1 },
  149: { name: "Dragonite", gen: 1 },
  150: { name: "Mewtwo", gen: 1, forms: ["mega"] },
  151: { name: "Mew", gen: 1 },
  152: { name: "Chikorita", gen: 2 },
  153: { name: "Bayleef", gen: 2 },
  154: { name: "Meganium", gen: 2 },
  155: { name: "Cyndaquil", gen: 2 },
  156: { name: "Quilava", gen: 2 },
  157: { name: "Typhlosion", gen: 2, forms: ["hisui"] },
  158: { name: "Totodile", gen: 2 },
  159: { name: "Croconaw", gen: 2 },
  160: { name: "Feraligatr", gen: 2 },
  161: { name: "Sentret", gen: 2 },
  162: { name: "Furret", gen: 2 },
  163: { name: "Hoothoot", gen: 2 },
  164: { name: "Noctowl", gen: 2 },
  165: { name: "Ledyba", gen: 2 },
  166: { name: "Ledian", gen: 2 },
  167: { name: "Spinarak", gen: 2 },
  168: { name: "Ariados", gen: 2 },
  169: { name: "Crobat", gen: 2 },
  170: { name: "Chinchou", gen: 2 },
  171: { name: "Lanturn", gen: 2 },
  172: { name: "Pichu", gen: 2 },
  173: { name: "Cleffa", gen: 2 },
  174: { name: "Igglybuff", gen: 2 },
  175: { name: "Togepi", gen: 2 },
  176: { name: "Togetic", gen: 2 },
  177: { name: "Natu", gen: 2 },
  178: { name: "Xatu", gen: 2 },
  179: { name: "Mareep", gen: 2 },
  180: { name: "Flaaffy", gen: 2 },
  181: { name: "Ampharos", gen: 2, forms: ["mega"] },
  182: { name: "Bellossom", gen: 2 },
  183: { name: "Marill", gen: 2 },
  184: { name: "Azumarill", gen: 2 },
  185: { name: "Sudowoodo", gen: 2 },
  186: { name: "Politoed", gen: 2 },
  187: { name: "Hoppip", gen: 2 },
  188: { name: "Skiploom", gen: 2 },
  189: { name: "Jumpluff", gen: 2 },
  190: { name: "Aipom", gen: 2 },
  191: { name: "Sunkern", gen: 2 },
  192: { name: "Sunflora", gen: 2 },
  193: { name: "Yanma", gen: 2 },
  194: { name: "Wooper", gen: 2, forms: ["paldea"] },
  195: { name: "Quagsire", gen: 2 },
  196: { name: "Espeon", gen: 2 },
  197: { name: "Umbreon", gen: 2 },
  198: { name: "Murkrow", gen: 2 },
  199: { name: "Slowking", gen: 2, forms: ["galar"] },
  200: { name: "Misdreavus", gen: 2 },
  201: { name: "Unown", gen: 2, forms: ["attack", "defense", "speed"] },
  202: { name: "Wobbuffet", gen: 2 },
  203: { name: "Girafarig", gen: 2 },
  204: { name: "Pineco", gen: 2 },
  205: { name: "Forretress", gen: 2 },
  206: { name: "Dunsparce", gen: 2 },
  207: { name: "Gligar", gen: 2 },
  208: { name: "Steelix", gen: 2, forms: ["mega"] },
  209: { name: "Snubbull", gen: 2 },
  210: { name: "Granbull", gen: 2 },
  211: { name: "Qwilfish", gen: 2, forms: ["hisui"] },
  212: { name: "Scizor", gen: 2, forms: ["mega"] },
  213: { name: "Shuckle", gen: 2 },
  214: { name: "Heracross", gen: 2, forms: ["mega"] },
  215: { name: "Sneasel", gen: 2, forms: ["hisui"] },
  216: { name: "Teddiursa", gen: 2 },
  217: { name: "Ursaring", gen: 2 },
  218: { name: "Slugma", gen: 2 },
  219: { name: "Magcargo", gen: 2 },
  220: { name: "Swinub", gen: 2 },
  221: { name: "Piloswine", gen: 2 },
  222: { name: "Corsola", gen: 2, forms: ["galar"] },
  223: { name: "Remoraid", gen: 2 },
  224: { name: "Octillery", gen: 2 },
  225: { name: "Delibird", gen: 2 },
  226: { name: "Mantine", gen: 2 },
  227: { name: "Skarmory", gen: 2 },
  228: { name: "Houndour", gen: 2 },
  229: { name: "Houndoom", gen: 2, forms: ["mega"] },
  230: { name: "Kingdra", gen: 2 },
  231: { name: "Phanpy", gen: 2 },
  232: { name: "Donphan", gen: 2 },
  233: { name: "Porygon2", gen: 2 },
  234: { name: "Stantler", gen: 2 },
  235: { name: "Smeargle", gen: 2 },
  236: { name: "Tyrogue", gen: 2 },
  237: { name: "Hitmontop", gen: 2 },
  238: { name: "Smoochum", gen: 2 },
  239: { name: "Elekid", gen: 2 },
  240: { name: "Magby", gen: 2 },
  241: { name: "Miltank", gen: 2 },
  242: { name: "Blissey", gen: 2 },
  243: { name: "Raikou", gen: 2 },
  244: { name: "Entei", gen: 2 },
  245: { name: "Suicune", gen: 2 },
  246: { name: "Larvitar", gen: 2 },
  247: { name: "Pupitar", gen: 2 },
  248: { name: "Tyranitar", gen: 2, forms: ["mega"] },
  249: { name: "Lugia", gen: 2 },
  250: { name: "Ho-Oh", gen: 2 },
  251: { name: "Celebi", gen: 2 },
  252: { name: "Treecko", gen: 3 },
  253: { name: "Grovyle", gen: 3 },
  254: { name: "Sceptile", gen: 3, forms: ["mega"] },
  255: { name: "Torchic", gen: 3 },
  256: { name: "Combusken", gen: 3 },
  257: { name: "Blaziken", gen: 3, forms: ["mega"] },
  258: { name: "Mudkip", gen: 3 },
  259: { name: "Marshtomp", gen: 3 },
  260: { name: "Swampert", gen: 3, forms: ["mega"] },
  261: { name: "Poochyena", gen: 3 },
  262: { name: "Mightyena", gen: 3 },
  263: { name: "Zigzagoon", gen: 3, forms: ["galar"] },
  264: { name: "Linoone", gen: 3, forms: ["galar"] },
  265: { name: "Wurmple", gen: 3 },
  266: { name: "Silcoon", gen: 3 },
  267: { name: "Beautifly", gen: 3 },
  268: { name: "Cascoon", gen: 3 },
  269: { name: "Dustox", gen: 3 },
  270: { name: "Lotad", gen: 3 },
  271: { name: "Lombre", gen: 3 },
  272: { name: "Ludicolo", gen: 3 },
  273: { name: "Seedot", gen: 3 },
  274: { name: "Nuzleaf", gen: 3 },
  275: { name: "Shiftry", gen: 3 },
  276: { name: "Taillow", gen: 3 },
  277: { name: "Swellow", gen: 3 },
  278: { name: "Wingull", gen: 3 },
  279: { name: "Pelipper", gen: 3 },
  280: { name: "Ralts", gen: 3 },
  281: { name: "Kirlia", gen: 3 },
  282: { name: "Gardevoir", gen: 3, forms: ["mega"] },
  283: { name: "Surskit", gen: 3 },
  284: { name: "Masquerain", gen: 3 },
  285: { name: "Shroomish", gen: 3 },
  286: { name: "Breloom", gen: 3 },
  287: { name: "Slakoth", gen: 3 },
  288: { name: "Vigoroth", gen: 3 },
  289: { name: "Slaking", gen: 3 },
  290: { name: "Nincada", gen: 3 },
  291: { name: "Ninjask", gen: 3 },
  292: { name: "Shedinja", gen: 3 },
  293: { name: "Whismur", gen: 3 },
  294: { name: "Loudred", gen: 3 },
  295: { name: "Exploud", gen: 3 },
  296: { name: "Makuhita", gen: 3 },
  297: { name: "Hariyama", gen: 3 },
  298: { name: "Azurill", gen: 3 },
  299: { name: "Nosepass", gen: 3 },
  300: { name: "Skitty", gen: 3 },
  301: { name: "Delcatty", gen: 3 },
  302: { name: "Sableye", gen: 3, forms: ["mega"] },
  303: { name: "Mawile", gen: 3, forms: ["mega"] },
  304: { name: "Aron", gen: 3 },
  305: { name: "Lairon", gen: 3 },
  306: { name: "Aggron", gen: 3, forms: ["mega"] },
  307: { name: "Meditite", gen: 3 },
  308: { name: "Medicham", gen: 3, forms: ["mega"] },
  309: { name: "Electrike", gen: 3 },
  310: { name: "Manectric", gen: 3, forms: ["mega"] },
  311: { name: "Plusle", gen: 3 },
  312: { name: "Minun", gen: 3 },
  313: { name: "Volbeat", gen: 3 },
  314: { name: "Illumise", gen: 3 },
  315: { name: "Roselia", gen: 3 },
  316: { name: "Gulpin", gen: 3 },
  317: { name: "Swalot", gen: 3 },
  318: { name: "Carvanha", gen: 3 },
  319: { name: "Sharpedo", gen: 3, forms: ["mega"] },
  320: { name: "Wailmer", gen: 3 },
  321: { name: "Wailord", gen: 3 },
  322: { name: "Numel", gen: 3 },
  323: { name: "Camerupt", gen: 3, forms: ["mega"] },
  324: { name: "Torkoal", gen: 3 },
  325: { name: "Spoink", gen: 3 },
  326: { name: "Grumpig", gen: 3 },
  327: { name: "Spinda", gen: 3 },
  328: { name: "Trapinch", gen: 3 },
  329: { name: "Vibrava", gen: 3 },
  330: { name: "Flygon", gen: 3 },
  331: { name: "Cacnea", gen: 3 },
  332: { name: "Cacturne", gen: 3 },
  333: { name: "Swablu", gen: 3 },
  334: { name: "Altaria", gen: 3, forms: ["mega"] },
  335: { name: "Zangoose", gen: 3 },
  336: { name: "Seviper", gen: 3 },
  337: { name: "Lunatone", gen: 3 },
  338: { name: "Solrock", gen: 3 },
  339: { name: "Barboach", gen: 3 },
  340: { name: "Whiscash", gen: 3 },
  341: { name: "Corphish", gen: 3 },
  342: { name: "Crawdaunt", gen: 3 },
  343: { name: "Baltoy", gen: 3 },
  344: { name: "Claydol", gen: 3 },
  345: { name: "Lileep", gen: 3 },
  346: { name: "Cradily", gen: 3 },
  347: { name: "Anorith", gen: 3 },
  348: { name: "Armaldo", gen: 3 },
  349: { name: "Feebas", gen: 3 },
  350: { name: "Milotic", gen: 3 },
  351: { name: "Castform", gen: 3, forms: ["rainy", "sunny", "snowy"] },
  352: { name: "Kecleon", gen: 3 },
  353: { name: "Shuppet", gen: 3 },
  354: { name: "Banette", gen: 3, forms: ["mega"] },
  355: { name: "Duskull", gen: 3 },
  356: { name: "Dusclops", gen: 3 },
  357: { name: "Tropius", gen: 3 },
  358: { name: "Chimecho", gen: 3 },
  359: { name: "Absol", gen: 3, forms: ["mega"] },
  360: { name: "Wynaut", gen: 3 },
  361: { name: "Snorunt", gen: 3 },
  362: { name: "Glalie", gen: 3, forms: ["mega"] },
  363: { name: "Spheal", gen: 3 },
  364: { name: "Sealeo", gen: 3 },
  365: { name: "Walrein", gen: 3 },
  366: { name: "Clamperl", gen: 3 },
  367: { name: "Huntail", gen: 3 },
  368: { name: "Gorebyss", gen: 3 },
  369: { name: "Relicanth", gen: 3 },
  370: { name: "Luvdisc", gen: 3 },
  371: { name: "Bagon", gen: 3 },
  372: { name: "Shelgon", gen: 3 },
  373: { name: "Salamence", gen: 3, forms: ["mega"] },
  374: { name: "Beldum", gen: 3 },
  375: { name: "Metang", gen: 3 },
  376: { name: "Metagross", gen: 3, forms: ["mega"] },
  377: { name: "Regirock", gen: 3 },
  378: { name: "Regice", gen: 3 },
  379: { name: "Registeel", gen: 3 },
  380: { name: "Latias", gen: 3, forms: ["mega"] },
  381: { name: "Latios", gen: 3, forms: ["mega"] },
  382: { name: "Kyogre", gen: 3, forms: ["primal"] },
  383: { name: "Groudon", gen: 3, forms: ["primal"] },
  384: { name: "Rayquaza", gen: 3, forms: ["mega"] },
  385: { name: "Jirachi", gen: 3 },
  386: { name: "Deoxys", gen: 3, forms: ["attack", "defense", "speed"] },
  387: { name: "Turtwig", gen: 4 },
  388: { name: "Grotle", gen: 4 },
  389: { name: "Torterra", gen: 4 },
  390: { name: "Chimchar", gen: 4 },
  391: { name: "Monferno", gen: 4 },
  392: { name: "Infernape", gen: 4 },
  393: { name: "Piplup", gen: 4 },
  394: { name: "Prinplup", gen: 4 },
  395: { name: "Empoleon", gen: 4 },
  396: { name: "Starly", gen: 4 },
  397: { name: "Staravia", gen: 4 },
  398: { name: "Staraptor", gen: 4 },
  399: { name: "Bidoof", gen: 4 },
  400: { name: "Bibarel", gen: 4 },
  401: { name: "Kricketot", gen: 4 },
  402: { name: "Kricketune", gen: 4 },
  403: { name: "Shinx", gen: 4 },
  404: { name: "Luxio", gen: 4 },
  405: { name: "Luxray", gen: 4 },
  406: { name: "Budew", gen: 4 },
  407: { name: "Roserade", gen: 4 },
  408: { name: "Cranidos", gen: 4 },
  409: { name: "Rampardos", gen: 4 },
  410: { name: "Shieldon", gen: 4 },
  411: { name: "Bastiodon", gen: 4 },
  412: { name: "Burmy", gen: 4 },
  413: { name: "Wormadam", gen: 4 },
  414: { name: "Mothim", gen: 4 },
  415: { name: "Combee", gen: 4 },
  416: { name: "Vespiquen", gen: 4 },
  417: { name: "Pachirisu", gen: 4 },
  418: { name: "Buizel", gen: 4 },
  419: { name: "Floatzel", gen: 4 },
  420: { name: "Cherubi", gen: 4 },
  421: { name: "Cherrim", gen: 4 },
  422: { name: "Shellos", gen: 4 },
  423: { name: "Gastrodon", gen: 4 },
  424: { name: "Ambipom", gen: 4 },
  425: { name: "Drifloon", gen: 4 },
  426: { name: "Drifblim", gen: 4 },
  427: { name: "Buneary", gen: 4 },
  428: { name: "Lopunny", gen: 4, forms: ["mega"] },
  429: { name: "Mismagius", gen: 4 },
  430: { name: "Honchkrow", gen: 4 },
  431: { name: "Glameow", gen: 4 },
  432: { name: "Purugly", gen: 4 },
  433: { name: "Chingling", gen: 4 },
  434: { name: "Stunky", gen: 4 },
  435: { name: "Skuntank", gen: 4 },
  436: { name: "Bronzor", gen: 4 },
  437: { name: "Bronzong", gen: 4 },
  438: { name: "Bonsly", gen: 4 },
  439: { name: "Mime Jr.", gen: 4 },
  440: { name: "Happiny", gen: 4 },
  441: { name: "Chatot", gen: 4 },
  442: { name: "Spiritomb", gen: 4 },
  443: { name: "Gible", gen: 4 },
  444: { name: "Gabite", gen: 4 },
  445: { name: "Garchomp", gen: 4, forms: ["mega"] },
  446: { name: "Munchlax", gen: 4 },
  447: { name: "Riolu", gen: 4 },
  448: { name: "Lucario", gen: 4, forms: ["mega"] },
  449: { name: "Hippopotas", gen: 4 },
  450: { name: "Hippowdon", gen: 4 },
  451: { name: "Skorupi", gen: 4 },
  452: { name: "Drapion", gen: 4 },
  453: { name: "Croagunk", gen: 4 },
  454: { name: "Toxicroak", gen: 4 },
  455: { name: "Carnivine", gen: 4 },
  456: { name: "Finneon", gen: 4 },
  457: { name: "Lumineon", gen: 4 },
  458: { name: "Mantyke", gen: 4 },
  459: { name: "Snover", gen: 4 },
  460: { name: "Abomasnow", gen: 4, forms: ["mega"] },
  461: { name: "Weavile", gen: 4 },
  462: { name: "Magnezone", gen: 4 },
  463: { name: "Lickilicky", gen: 4 },
  464: { name: "Rhyperior", gen: 4 },
  465: { name: "Tangrowth", gen: 4 },
  466: { name: "Electivire", gen: 4 },
  467: { name: "Magmortar", gen: 4 },
  468: { name: "Togekiss", gen: 4 },
  469: { name: "Yanmega", gen: 4 },
  470: { name: "Leafeon", gen: 4 },
  471: { name: "Glaceon", gen: 4 },
  472: { name: "Gliscor", gen: 4 },
  473: { name: "Mamoswine", gen: 4 },
  474: { name: "Porygon-Z", gen: 4 },
  475: { name: "Gallade", gen: 4, forms: ["mega"] },
  476: { name: "Probopass", gen: 4 },
  477: { name: "Dusknoir", gen: 4 },
  478: { name: "Froslass", gen: 4 },
  479: { name: "Rotom", gen: 4, forms: ["heat", "wash", "frost", "fan", "mow"] },
  480: { name: "Uxie", gen: 4 },
  481: { name: "Mesprit", gen: 4 },
  482: { name: "Azelf", gen: 4 },
  483: { name: "Dialga", gen: 4, forms: ["origin"] },
  484: { name: "Palkia", gen: 4, forms: ["origin"] },
  485: { name: "Heatran", gen: 4 },
  486: { name: "Regigigas", gen: 4 },
  487: { name: "Giratina", gen: 4, forms: ["origin"] },
  488: { name: "Cresselia", gen: 4 },
  489: { name: "Phione", gen: 4 },
  490: { name: "Manaphy", gen: 4 },
  491: { name: "Darkrai", gen: 4 },
  492: { name: "Shaymin", gen: 4, forms: ["sky"] },
  493: { name: "Arceus", gen: 4 },
  494: { name: "Victini", gen: 5 },
  495: { name: "Snivy", gen: 5 },
  496: { name: "Servine", gen: 5 },
  497: { name: "Serperior", gen: 5 },
  498: { name: "Tepig", gen: 5 },
  499: { name: "Pignite", gen: 5 },
  500: { name: "Emboar", gen: 5 },
  501: { name: "Oshawott", gen: 5 },
  502: { name: "Dewott", gen: 5 },
  503: { name: "Samurott", gen: 5, forms: ["hisui"] },
  504: { name: "Patrat", gen: 5 },
  505: { name: "Watchog", gen: 5 },
  506: { name: "Lillipup", gen: 5 },
  507: { name: "Herdier", gen: 5 },
  508: { name: "Stoutland", gen: 5 },
  509: { name: "Purrloin", gen: 5 },
  510: { name: "Liepard", gen: 5 },
  511: { name: "Pansage", gen: 5 },
  512: { name: "Simisage", gen: 5 },
  513: { name: "Pansear", gen: 5 },
  514: { name: "Simisear", gen: 5 },
  515: { name: "Panpour", gen: 5 },
  516: { name: "Simipour", gen: 5 },
  517: { name: "Munna", gen: 5 },
  518: { name: "Musharna", gen: 5 },
  519: { name: "Pidove", gen: 5 },
  520: { name: "Tranquill", gen: 5 },
  521: { name: "Unfezant", gen: 5 },
  522: { name: "Blitzle", gen: 5 },
  523: { name: "Zebstrika", gen: 5 },
  524: { name: "Roggenrola", gen: 5 },
  525: { name: "Boldore", gen: 5 },
  526: { name: "Gigalith", gen: 5 },
  527: { name: "Woobat", gen: 5 },
  528: { name: "Swoobat", gen: 5 },
  529: { name: "Drilbur", gen: 5 },
  530: { name: "Excadrill", gen: 5 },
  531: { name: "Audino", gen: 5, forms: ["mega"] },
  532: { name: "Timburr", gen: 5 },
  533: { name: "Gurdurr", gen: 5 },
  534: { name: "Conkeldurr", gen: 5 },
  535: { name: "Tympole", gen: 5 },
  536: { name: "Palpitoad", gen: 5 },
  537: { name: "Seismitoad", gen: 5 },
  538: { name: "Throh", gen: 5 },
  539: { name: "Sawk", gen: 5 },
  540: { name: "Sewaddle", gen: 5 },
  541: { name: "Swadloon", gen: 5 },
  542: { name: "Leavanny", gen: 5 },
  543: { name: "Venipede", gen: 5 },
  544: { name: "Whirlipede", gen: 5 },
  545: { name: "Scolipede", gen: 5 },
  546: { name: "Cottonee", gen: 5 },
  547: { name: "Whimsicott", gen: 5 },
  548: { name: "Petilil", gen: 5 },
  549: { name: "Lilligant", gen: 5, forms: ["hisui"] },
  550: { name: "Basculin", gen: 5, forms: ["hisui"] },
  551: { name: "Sandile", gen: 5 },
  552: { name: "Krokorok", gen: 5 },
  553: { name: "Krookodile", gen: 5 },
  554: { name: "Darumaka", gen: 5, forms: ["galar"] },
  555: { name: "Darmanitan", gen: 5, forms: ["galar"] },
  556: { name: "Maractus", gen: 5 },
  557: { name: "Dwebble", gen: 5 },
  558: { name: "Crustle", gen: 5 },
  559: { name: "Scraggy", gen: 5 },
  560: { name: "Scrafty", gen: 5 },
  561: { name: "Sigilyph", gen: 5 },
  562: { name: "Yamask", gen: 5, forms: ["galar"] },
  563: { name: "Cofagrigus", gen: 5 },
  564: { name: "Tirtouga", gen: 5 },
  565: { name: "Carracosta", gen: 5 },
  566: { name: "Archen", gen: 5 },
  567: { name: "Archeops", gen: 5 },
  568: { name: "Trubbish", gen: 5 },
  569: { name: "Garbodor", gen: 5, forms: ["gmax"] },
  570: { name: "Zorua", gen: 5, forms: ["hisui"] },
  571: { name: "Zoroark", gen: 5, forms: ["hisui"] },
  572: { name: "Minccino", gen: 5 },
  573: { name: "Cinccino", gen: 5 },
  574: { name: "Gothita", gen: 5 },
  575: { name: "Gothorita", gen: 5 },
  576: { name: "Gothitelle", gen: 5 },
  577: { name: "Solosis", gen: 5 },
  578: { name: "Duosion", gen: 5 },
  579: { name: "Reuniclus", gen: 5 },
  580: { name: "Ducklett", gen: 5 },
  581: { name: "Swanna", gen: 5 },
  582: { name: "Vanillite", gen: 5 },
  583: { name: "Vanillish", gen: 5 },
  584: { name: "Vanilluxe", gen: 5 },
  585: { name: "Deerling", gen: 5 },
  586: { name: "Sawsbuck", gen: 5 },
  587: { name: "Emolga", gen: 5 },
  588: { name: "Karrablast", gen: 5 },
  589: { name: "Escavalier", gen: 5 },
  590: { name: "Foongus", gen: 5 },
  591: { name: "Amoonguss", gen: 5 },
  592: { name: "Frillish", gen: 5 },
  593: { name: "Jellicent", gen: 5 },
  594: { name: "Alomomola", gen: 5 },
  595: { name: "Joltik", gen: 5 },
  596: { name: "Galvantula", gen: 5 },
  597: { name: "Ferroseed", gen: 5 },
  598: { name: "Ferrothorn", gen: 5 },
  599: { name: "Klink", gen: 5 },
  600: { name: "Klang", gen: 5 },
  601: { name: "Klinklang", gen: 5 },
  602: { name: "Tynamo", gen: 5 },
  603: { name: "Eelektrik", gen: 5 },
  604: { name: "Eelektross", gen: 5 },
  605: { name: "Elgyem", gen: 5 },
  606: { name: "Beheeyem", gen: 5 },
  607: { name: "Litwick", gen: 5 },
  608: { name: "Lampent", gen: 5 },
  609: { name: "Chandelure", gen: 5 },
  610: { name: "Axew", gen: 5 },
  611: { name: "Fraxure", gen: 5 },
  612: { name: "Haxorus", gen: 5 },
  613: { name: "Cubchoo", gen: 5 },
  614: { name: "Beartic", gen: 5 },
  615: { name: "Cryogonal", gen: 5 },
  616: { name: "Shelmet", gen: 5 },
  617: { name: "Accelgor", gen: 5 },
  618: { name: "Stunfisk", gen: 5, forms: ["galar"] },
  619: { name: "Mienfoo", gen: 5 },
  620: { name: "Mienshao", gen: 5 },
  621: { name: "Druddigon", gen: 5 },
  622: { name: "Golett", gen: 5 },
  623: { name: "Golurk", gen: 5 },
  624: { name: "Pawniard", gen: 5 },
  625: { name: "Bisharp", gen: 5 },
  626: { name: "Bouffalant", gen: 5 },
  627: { name: "Rufflet", gen: 5 },
  628: { name: "Braviary", gen: 5, forms: ["hisui"] },
  629: { name: "Vullaby", gen: 5 },
  630: { name: "Mandibuzz", gen: 5 },
  631: { name: "Heatmor", gen: 5 },
  632: { name: "Durant", gen: 5 },
  633: { name: "Deino", gen: 5 },
  634: { name: "Zweilous", gen: 5 },
  635: { name: "Hydreigon", gen: 5 },
  636: { name: "Larvesta", gen: 5 },
  637: { name: "Volcarona", gen: 5 },
  638: { name: "Cobalion", gen: 5 },
  639: { name: "Terrakion", gen: 5 },
  640: { name: "Virizion", gen: 5 },
  641: { name: "Tornadus", gen: 5, forms: ["therian"] },
  642: { name: "Thundurus", gen: 5, forms: ["therian"] },
  643: { name: "Reshiram", gen: 5 },
  644: { name: "Zekrom", gen: 5 },
  645: { name: "Landorus", gen: 5, forms: ["therian"] },
  646: { name: "Kyurem", gen: 5, forms: ["black", "white"] },
  647: { name: "Keldeo", gen: 5, forms: ["resolute"] },
  648: { name: "Meloetta", gen: 5, forms: ["pirouette"] },
  649: { name: "Genesect", gen: 5, forms: ["douse", "shock", "burn", "chill"] },
  650: { name: "Chespin", gen: 6 },
  651: { name: "Quilladin", gen: 6 },
  652: { name: "Chesnaught", gen: 6 },
  653: { name: "Fennekin", gen: 6 },
  654: { name: "Braixen", gen: 6 },
  655: { name: "Delphox", gen: 6 },
  656: { name: "Froakie", gen: 6 },
  657: { name: "Frogadier", gen: 6 },
  658: { name: "Greninja", gen: 6, forms: ["ash"] },
  659: { name: "Bunnelby", gen: 6 },
  660: { name: "Diggersby", gen: 6 },
  661: { name: "Fletchling", gen: 6 },
  662: { name: "Fletchinder", gen: 6 },
  663: { name: "Talonflame", gen: 6 },
  664: { name: "Scatterbug", gen: 6 },
  665: { name: "Spewpa", gen: 6 },
  666: { name: "Vivillon", gen: 6 },
  667: { name: "Litleo", gen: 6 },
  668: { name: "Pyroar", gen: 6 },
  669: { name: "Flabebe", gen: 6 },
  670: { name: "Floette", gen: 6 },
  671: { name: "Florges", gen: 6 },
  672: { name: "Skiddo", gen: 6 },
  673: { name: "Gogoat", gen: 6 },
  674: { name: "Pancham", gen: 6 },
  675: { name: "Pangoro", gen: 6 },
  676: { name: "Furfrou", gen: 6 },
  677: { name: "Espurr", gen: 6 },
  678: { name: "Meowstic", gen: 6 },
  679: { name: "Honedge", gen: 6 },
  680: { name: "Doublade", gen: 6 },
  681: { name: "Aegislash", gen: 6 },
  682: { name: "Spritzee", gen: 6 },
  683: { name: "Aromatisse", gen: 6 },
  684: { name: "Swirlix", gen: 6 },
  685: { name: "Slurpuff", gen: 6 },
  686: { name: "Inkay", gen: 6 },
  687: { name: "Malamar", gen: 6 },
  688: { name: "Binacle", gen: 6 },
  689: { name: "Barbaracle", gen: 6 },
  690: { name: "Skrelp", gen: 6 },
  691: { name: "Dragalge", gen: 6 },
  692: { name: "Clauncher", gen: 6 },
  693: { name: "Clawitzer", gen: 6 },
  694: { name: "Helioptile", gen: 6 },
  695: { name: "Heliolisk", gen: 6 },
  696: { name: "Tyrunt", gen: 6 },
  697: { name: "Tyrantrum", gen: 6 },
  698: { name: "Amaura", gen: 6 },
  699: { name: "Aurorus", gen: 6 },
  700: { name: "Sylveon", gen: 6 },
  701: { name: "Hawlucha", gen: 6 },
  702: { name: "Dedenne", gen: 6 },
  703: { name: "Carbink", gen: 6 },
  704: { name: "Goomy", gen: 6 },
  705: { name: "Sliggoo", gen: 6, forms: ["hisui"] },
  706: { name: "Goodra", gen: 6, forms: ["mega", "hisui"] },
  707: { name: "Klefki", gen: 6 },
  708: { name: "Phantump", gen: 6 },
  709: { name: "Trevenant", gen: 6 },
  710: { name: "Pumpkaboo", gen: 6 },
  711: { name: "Gourgeist", gen: 6 },
  712: { name: "Bergmite", gen: 6 },
  713: { name: "Avalugg", gen: 6, forms: ["hisui"] },
  714: { name: "Noibat", gen: 6 },
  715: { name: "Noivern", gen: 6 },
  716: { name: "Xerneas", gen: 6 },
  717: { name: "Yveltal", gen: 6 },
  718: { name: "Zygarde", gen: 6, forms: ["10", "complete"] },
  719: { name: "Diancie", gen: 6, forms: ["mega"] },
  720: { name: "Hoopa", gen: 6, forms: ["unbound"] },
  721: { name: "Volcanion", gen: 6 },
  722: { name: "Rowlet", gen: 7 },
  723: { name: "Dartrix", gen: 7 },
  724: { name: "Decidueye", gen: 7, forms: ["hisui"] },
  725: { name: "Litten", gen: 7 },
  726: { name: "Torracat", gen: 7 },
  727: { name: "Incineroar", gen: 7 },
  728: { name: "Popplio", gen: 7 },
  729: { name: "Brionne", gen: 7 },
  730: { name: "Primarina", gen: 7 },
  731: { name: "Pikipek", gen: 7 },
  732: { name: "Trumbeak", gen: 7 },
  733: { name: "Toucannon", gen: 7 },
  734: { name: "Yungoos", gen: 7 },
  735: { name: "Gumshoos", gen: 7 },
  736: { name: "Grubbin", gen: 7 },
  737: { name: "Charjabug", gen: 7 },
  738: { name: "Vikavolt", gen: 7 },
  739: { name: "Crabrawler", gen: 7 },
  740: { name: "Crabominable", gen: 7 },
  741: { name: "Oricorio", gen: 7 },
  742: { name: "Cutiefly", gen: 7 },
  743: { name: "Ribombee", gen: 7, forms: ["gmax"] },
  744: { name: "Rockruff", gen: 7 },
  745: { name: "Lycanroc", gen: 7 },
  746: { name: "Wishiwashi", gen: 7 },
  747: { name: "Mareanie", gen: 7 },
  748: { name: "Toxapex", gen: 7 },
  749: { name: "Mudbray", gen: 7 },
  750: { name: "Mudsdale", gen: 7 },
  751: { name: "Dewpider", gen: 7 },
  752: { name: "Araquanid", gen: 7 },
  753: { name: "Fomantis", gen: 7 },
  754: { name: "Lurantis", gen: 7 },
  755: { name: "Morelull", gen: 7 },
  756: { name: "Shiinotic", gen: 7 },
  757: { name: "Salandit", gen: 7 },
  758: { name: "Salazzle", gen: 7 },
  759: { name: "Stufful", gen: 7 },
  760: { name: "Bewear", gen: 7 },
  761: { name: "Bounsweet", gen: 7 },
  762: { name: "Steenee", gen: 7 },
  763: { name: "Tsareena", gen: 7 },
  764: { name: "Comfey", gen: 7 },
  765: { name: "Oranguru", gen: 7 },
  766: { name: "Passimian", gen: 7 },
  767: { name: "Wimpod", gen: 7 },
  768: { name: "Golisopod", gen: 7 },
  769: { name: "Sandygast", gen: 7 },
  770: { name: "Palossand", gen: 7 },
  771: { name: "Pyukumuku", gen: 7 },
  772: { name: "Type: Null", gen: 7 },
  773: { name: "Silvally", gen: 7 },
  774: { name: "Minior", gen: 7 },
  775: { name: "Komala", gen: 7 },
  776: { name: "Turtonator", gen: 7 },
  777: { name: "Togedemaru", gen: 7 },
  778: { name: "Mimikyu", gen: 7 },
  779: { name: "Bruxish", gen: 7 },
  780: { name: "Drampa", gen: 7 },
  781: { name: "Dhelmise", gen: 7 },
  782: { name: "Jangmo-o", gen: 7 },
  783: { name: "Hakamo-o", gen: 7 },
  784: { name: "Kommo-o", gen: 7 },
  785: { name: "Tapu Koko", gen: 7 },
  786: { name: "Tapu Lele", gen: 7 },
  787: { name: "Tapu Bulu", gen: 7 },
  788: { name: "Tapu Fini", gen: 7 },
  789: { name: "Cosmog", gen: 7 },
  790: { name: "Cosmoem", gen: 7 },
  791: { name: "Solgaleo", gen: 7 },
  792: { name: "Lunala", gen: 7 },
  793: { name: "Nihilego", gen: 7 },
  794: { name: "Buzzwole", gen: 7 },
  795: { name: "Pheromosa", gen: 7 },
  796: { name: "Xurkitree", gen: 7 },
  797: { name: "Celesteela", gen: 7 },
  798: { name: "Kartana", gen: 7 },
  799: { name: "Guzzlord", gen: 7 },
  800: { name: "Necrozma", gen: 7, forms: ["dawn-wings", "dusk-mane", "ultra"] },
  801: { name: "Magearna", gen: 7 },
  802: { name: "Marshadow", gen: 7 },
  803: { name: "Poipole", gen: 7 },
  804: { name: "Naganadel", gen: 7 },
  805: { name: "Stakataka", gen: 7 },
  806: { name: "Blacephalon", gen: 7 },
  807: { name: "Zeraora", gen: 7 },
  808: { name: "Meltan", gen: 7 },
  809: { name: "Melmetal", gen: 7, forms: ["gmax"] },
  810: { name: "Grookey", gen: 8 },
  811: { name: "Thwackey", gen: 8 },
  812: { name: "Rillaboom", gen: 8, forms: ["gmax"] },
  813: { name: "Scorbunny", gen: 8 },
  814: { name: "Raboot", gen: 8 },
  815: { name: "Cinderace", gen: 8, forms: ["gmax"] },
  816: { name: "Sobble", gen: 8 },
  817: { name: "Drizzile", gen: 8 },
  818: { name: "Inteleon", gen: 8, forms: ["gmax"] },
  819: { name: "Skwovet", gen: 8 },
  820: { name: "Greedent", gen: 8 },
  821: { name: "Rookidee", gen: 8 },
  822: { name: "Corvisquire", gen: 8 },
  823: { name: "Corviknight", gen: 8, forms: ["gmax"] },
  824: { name: "Blipbug", gen: 8 },
  825: { name: "Dottler", gen: 8 },
  826: { name: "Orbeetle", gen: 8, forms: ["gmax"] },
  827: { name: "Nickit", gen: 8 },
  828: { name: "Thievul", gen: 8 },
  829: { name: "Gossifleur", gen: 8 },
  830: { name: "Eldegoss", gen: 8 },
  831: { name: "Wooloo", gen: 8 },
  832: { name: "Dubwool", gen: 8 },
  833: { name: "Chewtle", gen: 8 },
  834: { name: "Drednaw", gen: 8, forms: ["gmax"] },
  835: { name: "Yamper", gen: 8 },
  836: { name: "Boltund", gen: 8 },
  837: { name: "Rolycoly", gen: 8 },
  838: { name: "Carkol", gen: 8 },
  839: { name: "Coalossal", gen: 8, forms: ["gmax"] },
  840: { name: "Applin", gen: 8 },
  841: { name: "Flapple", gen: 8, forms: ["gmax"] },
  842: { name: "Appletun", gen: 8, forms: ["gmax"] },
  843: { name: "Silicobra", gen: 8 },
  844: { name: "Sandaconda", gen: 8, forms: ["gmax"] },
  845: { name: "Cramorant", gen: 8 },
  846: { name: "Arrokuda", gen: 8 },
  847: { name: "Barraskewda", gen: 8 },
  848: { name: "Toxel", gen: 8 },
  849: { name: "Toxtricity", gen: 8, forms: ["gmax"] },
  850: { name: "Sizzlipede", gen: 8 },
  851: { name: "Centiskorch", gen: 8, forms: ["gmax"] },
  852: { name: "Clobbopus", gen: 8 },
  853: { name: "Grapploct", gen: 8 },
  854: { name: "Sinistea", gen: 8 },
  855: { name: "Polteageist", gen: 8 },
  856: { name: "Hatenna", gen: 8 },
  857: { name: "Hattrem", gen: 8 },
  858: { name: "Hatterene", gen: 8, forms: ["gmax"] },
  859: { name: "Impidimp", gen: 8 },
  860: { name: "Morgrem", gen: 8 },
  861: { name: "Grimmsnarl", gen: 8, forms: ["gmax"] },
  862: { name: "Obstagoon", gen: 8 },
  863: { name: "Perrserker", gen: 8 },
  864: { name: "Cursola", gen: 8 },
  865: { name: "Sirfetch'd", gen: 8 },
  866: { name: "Mr. Rime", gen: 8 },
  867: { name: "Runerigus", gen: 8 },
  868: { name: "Milcery", gen: 8 },
  869: { name: "Alcremie", gen: 8, forms: ["gmax"] },
  870: { name: "Falinks", gen: 8 },
  871: { name: "Pincurchin", gen: 8 },
  872: { name: "Snom", gen: 8 },
  873: { name: "Frosmoth", gen: 8 },
  874: { name: "Stonjourner", gen: 8 },
  875: { name: "Eiscue", gen: 8 },
  876: { name: "Indeedee", gen: 8 },
  877: { name: "Morpeko", gen: 8 },
  878: { name: "Cufant", gen: 8 },
  879: { name: "Copperajah", gen: 8, forms: ["gmax"] },
  880: { name: "Dracozolt", gen: 8 },
  881: { name: "Arctozolt", gen: 8 },
  882: { name: "Dracovish", gen: 8 },
  883: { name: "Arctovish", gen: 8 },
  884: { name: "Duraludon", gen: 8, forms: ["gmax"] },
  885: { name: "Dreepy", gen: 8 },
  886: { name: "Drakloak", gen: 8 },
  887: { name: "Dragapult", gen: 8 },
  888: { name: "Zacian", gen: 8 },
  889: { name: "Zamazenta", gen: 8 },
  890: { name: "Eternatus", gen: 8, forms: ["eternamax"] },
  891: { name: "Kubfu", gen: 8 },
  892: { name: "Urshifu", gen: 8, forms: ["gmax"] },
  893: { name: "Zarude", gen: 8 },
  894: { name: "Regieleki", gen: 8 },
  895: { name: "Regidrago", gen: 8 },
  896: { name: "Glastrier", gen: 8 },
  897: { name: "Spectrier", gen: 8 },
  898: { name: "Calyrex", gen: 8 },
  899: { name: "Wyrdeer", gen: 8 },
  900: { name: "Kleavor", gen: 8 },
  901: { name: "Ursaluna", gen: 8 },
  902: { name: "Basculegion", gen: 8 },
  903: { name: "Sneasler", gen: 8 },
  904: { name: "Overqwil", gen: 8 },
  905: { name: "Enamorus", gen: 8 },
  906: { name: "Sprigatito", gen: 9 },
  907: { name: "Floragato", gen: 9 },
  908: { name: "Meowscarada", gen: 9 },
  909: { name: "Fuecoco", gen: 9 },
  910: { name: "Crocalor", gen: 9 },
  911: { name: "Skeledirge", gen: 9 },
  912: { name: "Quaxly", gen: 9 },
  913: { name: "Quaxwell", gen: 9 },
  914: { name: "Quaquaval", gen: 9 },
  915: { name: "Lechonk", gen: 9 },
  916: { name: "Oinkologne", gen: 9 },
  917: { name: "Tarountula", gen: 9 },
  918: { name: "Spidops", gen: 9 },
  919: { name: "Nymble", gen: 9 },
  920: { name: "Lokix", gen: 9 },
  921: { name: "Pawmi", gen: 9 },
  922: { name: "Pawmo", gen: 9 },
  923: { name: "Pawmot", gen: 9 },
  924: { name: "Tandemaus", gen: 9 },
  925: { name: "Maushold", gen: 9 },
  926: { name: "Fidough", gen: 9 },
  927: { name: "Dachsbun", gen: 9 },
  928: { name: "Smoliv", gen: 9 },
  929: { name: "Dolliv", gen: 9 },
  930: { name: "Arboliva", gen: 9 },
  931: { name: "Squawkabilly", gen: 9 },
  932: { name: "Nacli", gen: 9 },
  933: { name: "Naclstack", gen: 9 },
  934: { name: "Garganacl", gen: 9 },
  935: { name: "Charcadet", gen: 9 },
  936: { name: "Armarouge", gen: 9 },
  937: { name: "Ceruledge", gen: 9 },
  938: { name: "Tadbulb", gen: 9 },
  939: { name: "Bellibolt", gen: 9 },
  940: { name: "Wattrel", gen: 9 },
  941: { name: "Kilowattrel", gen: 9 },
  942: { name: "Maschiff", gen: 9 },
  943: { name: "Mabosstiff", gen: 9 },
  944: { name: "Shroodle", gen: 9 },
  945: { name: "Grafaiai", gen: 9 },
  946: { name: "Bramblin", gen: 9 },
  947: { name: "Brambleghast", gen: 9 },
  948: { name: "Toedscool", gen: 9 },
  949: { name: "Toedscruel", gen: 9 },
  950: { name: "Klawf", gen: 9 },
  951: { name: "Capsakid", gen: 9 },
  952: { name: "Scovillain", gen: 9 },
  953: { name: "Rellor", gen: 9 },
  954: { name: "Rabsca", gen: 9 },
  955: { name: "Flittle", gen: 9 },
  956: { name: "Espathra", gen: 9 },
  957: { name: "Tinkatink", gen: 9 },
  958: { name: "Tinkatuff", gen: 9 },
  959: { name: "Tinkaton", gen: 9 },
  960: { name: "Wiglett", gen: 9 },
  961: { name: "Wugtrio", gen: 9 },
  962: { name: "Bombirdier", gen: 9 },
  963: { name: "Finizen", gen: 9 },
  964: { name: "Palafin", gen: 9 },
  965: { name: "Varoom", gen: 9 },
  966: { name: "Revavroom", gen: 9 },
  967: { name: "Cyclizar", gen: 9 },
  968: { name: "Orthworm", gen: 9 },
  969: { name: "Glimmet", gen: 9 },
  970: { name: "Glimmora", gen: 9 },
  971: { name: "Greavard", gen: 9 },
  972: { name: "Houndstone", gen: 9 },
  973: { name: "Flamigo", gen: 9 },
  974: { name: "Cetoddle", gen: 9 },
  975: { name: "Cetitan", gen: 9 },
  976: { name: "Veluza", gen: 9 },
  977: { name: "Dondozo", gen: 9 },
  978: { name: "Tatsugiri", gen: 9 },
  979: { name: "Annihilape", gen: 9 },
  980: { name: "Clodsire", gen: 9 },
  981: { name: "Farigiraf", gen: 9 },
  982: { name: "Dudunsparce", gen: 9 },
  983: { name: "Kingambit", gen: 9 },
  984: { name: "Great Tusk", gen: 9 },
  985: { name: "Scream Tail", gen: 9 },
  986: { name: "Brute Bonnet", gen: 9 },
  987: { name: "Flutter Mane", gen: 9 },
  988: { name: "Slither Wing", gen: 9 },
  989: { name: "Sandy Shocks", gen: 9 },
  990: { name: "Iron Treads", gen: 9 },
  991: { name: "Iron Bundle", gen: 9 },
  992: { name: "Iron Hands", gen: 9 },
  993: { name: "Iron Jugulis", gen: 9 },
  994: { name: "Iron Moth", gen: 9 },
  995: { name: "Iron Thorns", gen: 9 },
  996: { name: "Frigibax", gen: 9 },
  997: { name: "Arctibax", gen: 9 },
  998: { name: "Baxcalibur", gen: 9 },
  999: { name: "Gimmighoul", gen: 9 },
  1000: { name: "Gholdengo", gen: 9 },
  1001: { name: "Wo-Chien", gen: 9 },
  1002: { name: "Chien-Pao", gen: 9 },
  1003: { name: "Ting-Lu", gen: 9 },
  1004: { name: "Chi-Yu", gen: 9 },
  1005: { name: "Roaring Moon", gen: 9 },
  1006: { name: "Iron Valiant", gen: 9 },
  1007: { name: "Koraidon", gen: 9 },
  1008: { name: "Miraidon", gen: 9 },
  1009: { name: "Walking Wake", gen: 9 },
  1010: { name: "Iron Leaves", gen: 9 },
  1011: { name: "Dipplin", gen: 9 },
  1012: { name: "Poltchageist", gen: 9 },
  1013: { name: "Sinistcha", gen: 9 },
  1014: { name: "Okidogi", gen: 9 },
  1015: { name: "Munkidori", gen: 9 },
  1016: { name: "Fezandipiti", gen: 9 },
  1017: { name: "Ogerpon", gen: 9 },
  1018: { name: "Archaludon", gen: 9 },
  1019: { name: "Hydrapple", gen: 9 },
  1020: { name: "Gouging Fire", gen: 9 },
  1021: { name: "Raging Bolt", gen: 9 },
  1022: { name: "Iron Boulder", gen: 9 },
  1023: { name: "Iron Crown", gen: 9 },
  1024: { name: "Terapagos", gen: 9 },
  1025: { name: "Pecharunt", gen: 9 }
};

const GAME_INFO = {
  red: { generation: 1, name: "Pokemon Red", saveType: "gen1" },
  blue: { generation: 1, name: "Pokemon Blue", saveType: "gen1" },
  yellow: { generation: 1, name: "Pokemon Yellow", saveType: "gen1" },
  gold: { generation: 2, name: "Pokemon Gold", saveType: "gen2" },
  silver: { generation: 2, name: "Pokemon Silver", saveType: "gen2" },
  crystal: { generation: 2, name: "Pokemon Crystal", saveType: "gen2" },
  ruby: { generation: 3, name: "Pokemon Ruby", saveType: "gen3" },
  sapphire: { generation: 3, name: "Pokemon Sapphire", saveType: "gen3" },
  emerald: { generation: 3, name: "Pokemon Emerald", saveType: "gen3" },
  firered: { generation: 3, name: "Pokemon FireRed", saveType: "gen3" },
  leafgreen: { generation: 3, name: "Pokemon LeafGreen", saveType: "gen3" },
  diamond: { generation: 4, name: "Pokemon Diamond", saveType: "gen4" },
  pearl: { generation: 4, name: "Pokemon Pearl", saveType: "gen4" },
  platinum: { generation: 4, name: "Pokemon Platinum", saveType: "gen4" },
  heartgold: { generation: 4, name: "Pokemon HeartGold", saveType: "gen4" },
  soulsilver: { generation: 4, name: "Pokemon SoulSilver", saveType: "gen4" },
  black: { generation: 5, name: "Pokemon Black", saveType: "gen5" },
  white: { generation: 5, name: "Pokemon White", saveType: "gen5" },
  black2: { generation: 5, name: "Pokemon Black 2", saveType: "gen5" },
  white2: { generation: 5, name: "Pokemon White 2", saveType: "gen5" },
  x: { generation: 6, name: "Pokemon X", saveType: "gen6" },
  y: { generation: 6, name: "Pokemon Y", saveType: "gen6" },
  omegaruby: { generation: 6, name: "Pokemon Omega Ruby", saveType: "gen6" },
  alphasapphire: { generation: 6, name: "Pokemon Alpha Sapphire", saveType: "gen6" },
  sun: { generation: 7, name: "Pokemon Sun", saveType: "gen7sm" },
  moon: { generation: 7, name: "Pokemon Moon", saveType: "gen7sm" },
  ultrasun: { generation: 7, name: "Pokemon Ultra Sun", saveType: "gen7usum" },
  ultramoon: { generation: 7, name: "Pokemon Ultra Moon", saveType: "gen7usum" },
  sword: { generation: 8, name: "Pokemon Sword", saveType: "gen8swsh" },
  shield: { generation: 8, name: "Pokemon Shield", saveType: "gen8swsh" },
  brilliantdiamond: { generation: 8, name: "Pokemon Brilliant Diamond", saveType: "gen8bdsp" },
  shiningshpearl: { generation: 8, name: "Pokemon Shining Pearl", saveType: "gen8bdsp" },
  legendsarceus: { generation: 8, name: "Pokemon Legends Arceus", saveType: "gen8pla" },
  scarlet: { generation: 9, name: "Pokemon Scarlet", saveType: "gen9sv" },
  violet: { generation: 9, name: "Pokemon Violet", saveType: "gen9sv" }
};

function getPokemonName(id) {
  const pokemon = POKEMON[id];
  return pokemon ? pokemon.name : "Unknown";
}

function getGameList() {
  return Object.entries(GAME_INFO).map(([id, info]) => ({
    id,
    name: info.name,
    generation: info.generation
  }));
}

module.exports = { POKEMON, GAME_INFO, getPokemonName, getGameList };
