const SPECIES = [
  {id:0,name:'(Vacío)',form:null},{id:-1,name:'Ninguno',form:null},{id:-2,name:'Huevo',form:null},

  // Gen 1
  {id:1,name:'Bulbasaur',form:null},
  {id:2,name:'Ivysaur',form:null},
  {id:3,name:'Venusaur',form:null},
  {id:4,name:'Charmander',form:null},
  {id:5,name:'Charmeleon',form:null},
  {id:6,name:'Charizard',form:null},
  {id:7,name:'Squirtle',form:null},
  {id:8,name:'Wartortle',form:null},
  {id:9,name:'Blastoise',form:null},
  {id:10,name:'Caterpie',form:null},
  {id:11,name:'Metapod',form:null},
  {id:12,name:'Butterfree',form:null},
  {id:13,name:'Weedle',form:null},
  {id:14,name:'Kakuna',form:null},
  {id:15,name:'Beedrill',form:null},
  {id:16,name:'Pidgey',form:null},
  {id:17,name:'Pidgeotto',form:null},
  {id:18,name:'Pidgeot',form:null},
  {id:19,name:'Rattata',form:null},
  {id:20,name:'Raticate',form:null},
  {id:21,name:'Spearow',form:null},
  {id:22,name:'Fearow',form:null},
  {id:23,name:'Ekans',form:null},
  {id:24,name:'Arbok',form:null},
  {id:25,name:'Pikachu',form:null},
  {id:26,name:'Raichu',form:null},
  {id:27,name:'Sandshrew',form:null},
  {id:28,name:'Sandslash',form:null},
  {id:29,name:'Nidoran♀',form:null},
  {id:30,name:'Nidorina',form:null},
  {id:31,name:'Nidoqueen',form:null},
  {id:32,name:'Nidoran♂',form:null},
  {id:33,name:'Nidorino',form:null},
  {id:34,name:'Nidoking',form:null},
  {id:35,name:'Clefairy',form:null},
  {id:36,name:'Clefable',form:null},
  {id:37,name:'Vulpix',form:null},
  {id:38,name:'Ninetales',form:null},
  {id:39,name:'Jigglypuff',form:null},
  {id:40,name:'Wigglytuff',form:null},
  {id:41,name:'Zubat',form:null},
  {id:42,name:'Golbat',form:null},
  {id:43,name:'Oddish',form:null},
  {id:44,name:'Gloom',form:null},
  {id:45,name:'Vileplume',form:null},
  {id:46,name:'Paras',form:null},
  {id:47,name:'Parasect',form:null},
  {id:48,name:'Venonat',form:null},
  {id:49,name:'Venomoth',form:null},
  {id:50,name:'Diglett',form:null},
  {id:51,name:'Dugtrio',form:null},
  {id:52,name:'Meowth',form:null},
  {id:53,name:'Persian',form:null},
  {id:54,name:'Psyduck',form:null},
  {id:55,name:'Golduck',form:null},
  {id:56,name:'Mankey',form:null},
  {id:57,name:'Primeape',form:null},
  {id:58,name:'Growlithe',form:null},
  {id:59,name:'Arcanine',form:null},
  {id:60,name:'Poliwag',form:null},
  {id:61,name:'Poliwhirl',form:null},
  {id:62,name:'Poliwrath',form:null},
  {id:63,name:'Abra',form:null},
  {id:64,name:'Kadabra',form:null},
  {id:65,name:'Alakazam',form:null},
  {id:66,name:'Machop',form:null},
  {id:67,name:'Machoke',form:null},
  {id:68,name:'Machamp',form:null},
  {id:69,name:'Bellsprout',form:null},
  {id:70,name:'Weepinbell',form:null},
  {id:71,name:'Victreebel',form:null},
  {id:72,name:'Tentacool',form:null},
  {id:73,name:'Tentacruel',form:null},
  {id:74,name:'Geodude',form:null},
  {id:75,name:'Graveler',form:null},
  {id:76,name:'Golem',form:null},
  {id:77,name:'Ponyta',form:null},
  {id:78,name:'Rapidash',form:null},
  {id:79,name:'Slowpoke',form:null},
  {id:80,name:'Slowbro',form:null},
  {id:81,name:'Magnemite',form:null},
  {id:82,name:'Magneton',form:null},
  {id:83,name:'Farfetch\'d',form:null},
  {id:84,name:'Doduo',form:null},
  {id:85,name:'Dodrio',form:null},
  {id:86,name:'Seel',form:null},
  {id:87,name:'Dewgong',form:null},
  {id:88,name:'Grimer',form:null},
  {id:89,name:'Muk',form:null},
  {id:90,name:'Shellder',form:null},
  {id:91,name:'Cloyster',form:null},
  {id:92,name:'Gastly',form:null},
  {id:93,name:'Haunter',form:null},
  {id:94,name:'Gengar',form:null},
  {id:95,name:'Onix',form:null},
  {id:96,name:'Drowzee',form:null},
  {id:97,name:'Hypno',form:null},
  {id:98,name:'Krabby',form:null},
  {id:99,name:'Kingler',form:null},
  {id:100,name:'Voltorb',form:null},
  {id:101,name:'Electrode',form:null},
  {id:102,name:'Exeggcute',form:null},
  {id:103,name:'Exeggutor',form:null},
  {id:104,name:'Cubone',form:null},
  {id:105,name:'Marowak',form:null},
  {id:106,name:'Hitmonlee',form:null},
  {id:107,name:'Hitmonchan',form:null},
  {id:108,name:'Lickitung',form:null},
  {id:109,name:'Koffing',form:null},
  {id:110,name:'Weezing',form:null},
  {id:111,name:'Rhyhorn',form:null},
  {id:112,name:'Rhydon',form:null},
  {id:113,name:'Chansey',form:null},
  {id:114,name:'Tangela',form:null},
  {id:115,name:'Kangaskhan',form:null},
  {id:116,name:'Horsea',form:null},
  {id:117,name:'Seadra',form:null},
  {id:118,name:'Goldeen',form:null},
  {id:119,name:'Seaking',form:null},
  {id:120,name:'Staryu',form:null},
  {id:121,name:'Starmie',form:null},
  {id:122,name:'Mr. Mime',form:null},
  {id:123,name:'Scyther',form:null},
  {id:124,name:'Jynx',form:null},
  {id:125,name:'Electabuzz',form:null},
  {id:126,name:'Magmar',form:null},
  {id:127,name:'Pinsir',form:null},
  {id:128,name:'Tauros',form:null},
  {id:129,name:'Magikarp',form:null},
  {id:130,name:'Gyarados',form:null},
  {id:131,name:'Lapras',form:null},
  {id:132,name:'Ditto',form:null},
  {id:133,name:'Eevee',form:null},
  {id:134,name:'Vaporeon',form:null},
  {id:135,name:'Jolteon',form:null},
  {id:136,name:'Flareon',form:null},
  {id:137,name:'Porygon',form:null},
  {id:138,name:'Omanyte',form:null},
  {id:139,name:'Omastar',form:null},
  {id:140,name:'Kabuto',form:null},
  {id:141,name:'Kabutops',form:null},
  {id:142,name:'Aerodactyl',form:null},
  {id:143,name:'Snorlax',form:null},
  {id:144,name:'Articuno',form:null},
  {id:145,name:'Zapdos',form:null},
  {id:146,name:'Moltres',form:null},
  {id:147,name:'Dratini',form:null},
  {id:148,name:'Dragonair',form:null},
  {id:149,name:'Dragonite',form:null},
  {id:150,name:'Mewtwo',form:null},
  {id:151,name:'Mew',form:null},

  // Gen 2
  {id:152,name:'Chikorita',form:null},
  {id:153,name:'Bayleef',form:null},
  {id:154,name:'Meganium',form:null},
  {id:155,name:'Cyndaquil',form:null},
  {id:156,name:'Quilava',form:null},
  {id:157,name:'Typhlosion',form:null},
  {id:158,name:'Totodile',form:null},
  {id:159,name:'Croconaw',form:null},
  {id:160,name:'Feraligatr',form:null},
  {id:161,name:'Sentret',form:null},
  {id:162,name:'Furret',form:null},
  {id:163,name:'Hoothoot',form:null},
  {id:164,name:'Noctowl',form:null},
  {id:165,name:'Ledyba',form:null},
  {id:166,name:'Ledian',form:null},
  {id:167,name:'Spinarak',form:null},
  {id:168,name:'Ariados',form:null},
  {id:169,name:'Crobat',form:null},
  {id:170,name:'Chinchou',form:null},
  {id:171,name:'Lanturn',form:null},
  {id:172,name:'Pichu',form:null},
  {id:173,name:'Cleffa',form:null},
  {id:174,name:'Igglybuff',form:null},
  {id:175,name:'Togepi',form:null},
  {id:176,name:'Togetic',form:null},
  {id:177,name:'Natu',form:null},
  {id:178,name:'Xatu',form:null},
  {id:179,name:'Mareep',form:null},
  {id:180,name:'Flaaffy',form:null},
  {id:181,name:'Ampharos',form:null},
  {id:182,name:'Bellossom',form:null},
  {id:183,name:'Marill',form:null},
  {id:184,name:'Azumarill',form:null},
  {id:185,name:'Sudowoodo',form:null},
  {id:186,name:'Politoed',form:null},
  {id:187,name:'Hoppip',form:null},
  {id:188,name:'Skiploom',form:null},
  {id:189,name:'Jumpluff',form:null},
  {id:190,name:'Aipom',form:null},
  {id:191,name:'Sunkern',form:null},
  {id:192,name:'Sunflora',form:null},
  {id:193,name:'Yanma',form:null},
  {id:194,name:'Wooper',form:null},
  {id:195,name:'Quagsire',form:null},
  {id:196,name:'Espeon',form:null},
  {id:197,name:'Umbreon',form:null},
  {id:198,name:'Murkrow',form:null},
  {id:199,name:'Slowking',form:null},
  {id:200,name:'Misdreavus',form:null},
  {id:201,name:'Unown',form:null},
  {id:202,name:'Wobbuffet',form:null},
  {id:203,name:'Girafarig',form:null},
  {id:204,name:'Pineco',form:null},
  {id:205,name:'Forretress',form:null},
  {id:206,name:'Dunsparce',form:null},
  {id:207,name:'Gligar',form:null},
  {id:208,name:'Steelix',form:null},
  {id:209,name:'Snubbull',form:null},
  {id:210,name:'Granbull',form:null},
  {id:211,name:'Qwilfish',form:null},
  {id:212,name:'Scizor',form:null},
  {id:213,name:'Shuckle',form:null},
  {id:214,name:'Heracross',form:null},
  {id:215,name:'Sneasel',form:null},
  {id:216,name:'Teddiursa',form:null},
  {id:217,name:'Ursaring',form:null},
  {id:218,name:'Slugma',form:null},
  {id:219,name:'Magcargo',form:null},
  {id:220,name:'Swinub',form:null},
  {id:221,name:'Piloswine',form:null},
  {id:222,name:'Corsola',form:null},
  {id:223,name:'Remoraid',form:null},
  {id:224,name:'Octillery',form:null},
  {id:225,name:'Delibird',form:null},
  {id:226,name:'Mantine',form:null},
  {id:227,name:'Skarmory',form:null},
  {id:228,name:'Houndour',form:null},
  {id:229,name:'Houndoom',form:null},
  {id:230,name:'Kingdra',form:null},
  {id:231,name:'Phanpy',form:null},
  {id:232,name:'Donphan',form:null},
  {id:233,name:'Porygon2',form:null},
  {id:234,name:'Stantler',form:null},
  {id:235,name:'Smeargle',form:null},
  {id:236,name:'Tyrogue',form:null},
  {id:237,name:'Hitmontop',form:null},
  {id:238,name:'Smoochum',form:null},
  {id:239,name:'Elekid',form:null},
  {id:240,name:'Magby',form:null},
  {id:241,name:'Miltank',form:null},
  {id:242,name:'Blissey',form:null},
  {id:243,name:'Raikou',form:null},
  {id:244,name:'Entei',form:null},
  {id:245,name:'Suicune',form:null},
  {id:246,name:'Larvitar',form:null},
  {id:247,name:'Pupitar',form:null},
  {id:248,name:'Tyranitar',form:null},
  {id:249,name:'Lugia',form:null},
  {id:250,name:'Ho-Oh',form:null},
  {id:251,name:'Celebi',form:null},

  // Gen 3
  {id:252,name:'Treecko',form:null},
  {id:253,name:'Grovyle',form:null},
  {id:254,name:'Sceptile',form:null},
  {id:255,name:'Torchic',form:null},
  {id:256,name:'Combusken',form:null},
  {id:257,name:'Blaziken',form:null},
  {id:258,name:'Mudkip',form:null},
  {id:259,name:'Marshtomp',form:null},
  {id:260,name:'Swampert',form:null},
  {id:261,name:'Poochyena',form:null},
  {id:262,name:'Mightyena',form:null},
  {id:263,name:'Zigzagoon',form:null},
  {id:264,name:'Linoone',form:null},
  {id:265,name:'Wurmple',form:null},
  {id:266,name:'Silcoon',form:null},
  {id:267,name:'Beautifly',form:null},
  {id:268,name:'Cascoon',form:null},
  {id:269,name:'Dustox',form:null},
  {id:270,name:'Lotad',form:null},
  {id:271,name:'Lombre',form:null},
  {id:272,name:'Ludicolo',form:null},
  {id:273,name:'Seedot',form:null},
  {id:274,name:'Nuzleaf',form:null},
  {id:275,name:'Shiftry',form:null},
  {id:276,name:'Taillow',form:null},
  {id:277,name:'Swellow',form:null},
  {id:278,name:'Wingull',form:null},
  {id:279,name:'Pelipper',form:null},
  {id:280,name:'Ralts',form:null},
  {id:281,name:'Kirlia',form:null},
  {id:282,name:'Gardevoir',form:null},
  {id:283,name:'Surskit',form:null},
  {id:284,name:'Masquerain',form:null},
  {id:285,name:'Shroomish',form:null},
  {id:286,name:'Breloom',form:null},
  {id:287,name:'Slakoth',form:null},
  {id:288,name:'Vigoroth',form:null},
  {id:289,name:'Slaking',form:null},
  {id:290,name:'Nincada',form:null},
  {id:291,name:'Ninjask',form:null},
  {id:292,name:'Shedinja',form:null},
  {id:293,name:'Whismur',form:null},
  {id:294,name:'Loudred',form:null},
  {id:295,name:'Exploud',form:null},
  {id:296,name:'Makuhita',form:null},
  {id:297,name:'Hariyama',form:null},
  {id:298,name:'Azurill',form:null},
  {id:299,name:'Nosepass',form:null},
  {id:300,name:'Skitty',form:null},
  {id:301,name:'Delcatty',form:null},
  {id:302,name:'Sableye',form:null},
  {id:303,name:'Mawile',form:null},
  {id:304,name:'Aron',form:null},
  {id:305,name:'Lairon',form:null},
  {id:306,name:'Aggron',form:null},
  {id:307,name:'Meditite',form:null},
  {id:308,name:'Medicham',form:null},
  {id:309,name:'Electrike',form:null},
  {id:310,name:'Manectric',form:null},
  {id:311,name:'Plusle',form:null},
  {id:312,name:'Minun',form:null},
  {id:313,name:'Volbeat',form:null},
  {id:314,name:'Illumise',form:null},
  {id:315,name:'Roselia',form:null},
  {id:316,name:'Gulpin',form:null},
  {id:317,name:'Swalot',form:null},
  {id:318,name:'Carvanha',form:null},
  {id:319,name:'Sharpedo',form:null},
  {id:320,name:'Wailmer',form:null},
  {id:321,name:'Wailord',form:null},
  {id:322,name:'Numel',form:null},
  {id:323,name:'Camerupt',form:null},
  {id:324,name:'Torkoal',form:null},
  {id:325,name:'Spoink',form:null},
  {id:326,name:'Grumpig',form:null},
  {id:327,name:'Spinda',form:null},
  {id:328,name:'Trapinch',form:null},
  {id:329,name:'Vibrava',form:null},
  {id:330,name:'Flygon',form:null},
  {id:331,name:'Cacnea',form:null},
  {id:332,name:'Cacturne',form:null},
  {id:333,name:'Swablu',form:null},
  {id:334,name:'Altaria',form:null},
  {id:335,name:'Zangoose',form:null},
  {id:336,name:'Seviper',form:null},
  {id:337,name:'Lunatone',form:null},
  {id:338,name:'Solrock',form:null},
  {id:339,name:'Barboach',form:null},
  {id:340,name:'Whiscash',form:null},
  {id:341,name:'Corphish',form:null},
  {id:342,name:'Crawdaunt',form:null},
  {id:343,name:'Baltoy',form:null},
  {id:344,name:'Claydol',form:null},
  {id:345,name:'Lileep',form:null},
  {id:346,name:'Cradily',form:null},
  {id:347,name:'Anorith',form:null},
  {id:348,name:'Armaldo',form:null},
  {id:349,name:'Feebas',form:null},
  {id:350,name:'Milotic',form:null},
  {id:351,name:'Castform',form:null},
  {id:352,name:'Kecleon',form:null},
  {id:353,name:'Shuppet',form:null},
  {id:354,name:'Banette',form:null},
  {id:355,name:'Duskull',form:null},
  {id:356,name:'Dusclops',form:null},
  {id:357,name:'Tropius',form:null},
  {id:358,name:'Chimecho',form:null},
  {id:359,name:'Absol',form:null},
  {id:360,name:'Wynaut',form:null},
  {id:361,name:'Snorunt',form:null},
  {id:362,name:'Glalie',form:null},
  {id:363,name:'Spheal',form:null},
  {id:364,name:'Sealeo',form:null},
  {id:365,name:'Walrein',form:null},
  {id:366,name:'Clamperl',form:null},
  {id:367,name:'Huntail',form:null},
  {id:368,name:'Gorebyss',form:null},
  {id:369,name:'Relicanth',form:null},
  {id:370,name:'Luvdisc',form:null},
  {id:371,name:'Bagon',form:null},
  {id:372,name:'Shelgon',form:null},
  {id:373,name:'Salamence',form:null},
  {id:374,name:'Beldum',form:null},
  {id:375,name:'Metang',form:null},
  {id:376,name:'Metagross',form:null},
  {id:377,name:'Regirock',form:null},
  {id:378,name:'Regice',form:null},
  {id:379,name:'Registeel',form:null},
  {id:380,name:'Latias',form:null},
  {id:381,name:'Latios',form:null},
  {id:382,name:'Kyogre',form:null},
  {id:383,name:'Groudon',form:null},
  {id:384,name:'Rayquaza',form:null},
  {id:385,name:'Jirachi',form:null},
  {id:386,name:'Deoxys',form:null},

  // Gen 4
  {id:387,name:'Turtwig',form:null},
  {id:388,name:'Grotle',form:null},
  {id:389,name:'Torterra',form:null},
  {id:390,name:'Chimchar',form:null},
  {id:391,name:'Monferno',form:null},
  {id:392,name:'Infernape',form:null},
  {id:393,name:'Piplup',form:null},
  {id:394,name:'Prinplup',form:null},
  {id:395,name:'Empoleon',form:null},
  {id:396,name:'Starly',form:null},
  {id:397,name:'Staravia',form:null},
  {id:398,name:'Staraptor',form:null},
  {id:399,name:'Bidoof',form:null},
  {id:400,name:'Bibarel',form:null},
  {id:401,name:'Kricketot',form:null},
  {id:402,name:'Kricketune',form:null},
  {id:403,name:'Shinx',form:null},
  {id:404,name:'Luxio',form:null},
  {id:405,name:'Luxray',form:null},
  {id:406,name:'Budew',form:null},
  {id:407,name:'Roserade',form:null},
  {id:408,name:'Cranidos',form:null},
  {id:409,name:'Rampardos',form:null},
  {id:410,name:'Shieldon',form:null},
  {id:411,name:'Bastiodon',form:null},
  {id:412,name:'Burmy',form:null},
  {id:413,name:'Wormadam',form:null},
  {id:414,name:'Mothim',form:null},
  {id:415,name:'Combee',form:null},
  {id:416,name:'Vespiquen',form:null},
  {id:417,name:'Pachirisu',form:null},
  {id:418,name:'Buizel',form:null},
  {id:419,name:'Floatzel',form:null},
  {id:420,name:'Cherubi',form:null},
  {id:421,name:'Cherrim',form:null},
  {id:422,name:'Shellos',form:null},
  {id:423,name:'Gastrodon',form:null},
  {id:424,name:'Ambipom',form:null},
  {id:425,name:'Drifloon',form:null},
  {id:426,name:'Drifblim',form:null},
  {id:427,name:'Buneary',form:null},
  {id:428,name:'Lopunny',form:null},
  {id:429,name:'Mismagius',form:null},
  {id:430,name:'Honchkrow',form:null},
  {id:431,name:'Glameow',form:null},
  {id:432,name:'Purugly',form:null},
  {id:433,name:'Chingling',form:null},
  {id:434,name:'Stunky',form:null},
  {id:435,name:'Skuntank',form:null},
  {id:436,name:'Bronzor',form:null},
  {id:437,name:'Bronzong',form:null},
  {id:438,name:'Bonsly',form:null},
  {id:439,name:'Mime Jr.',form:null},
  {id:440,name:'Happiny',form:null},
  {id:441,name:'Chatot',form:null},
  {id:442,name:'Spiritomb',form:null},
  {id:443,name:'Gible',form:null},
  {id:444,name:'Gabite',form:null},
  {id:445,name:'Garchomp',form:null},
  {id:446,name:'Munchlax',form:null},
  {id:447,name:'Riolu',form:null},
  {id:448,name:'Lucario',form:null},
  {id:449,name:'Hippopotas',form:null},
  {id:450,name:'Hippowdon',form:null},
  {id:451,name:'Skorupi',form:null},
  {id:452,name:'Drapion',form:null},
  {id:453,name:'Croagunk',form:null},
  {id:454,name:'Toxicroak',form:null},
  {id:455,name:'Carnivine',form:null},
  {id:456,name:'Finneon',form:null},
  {id:457,name:'Lumineon',form:null},
  {id:458,name:'Mantyke',form:null},
  {id:459,name:'Snover',form:null},
  {id:460,name:'Abomasnow',form:null},
  {id:461,name:'Weavile',form:null},
  {id:462,name:'Magnezone',form:null},
  {id:463,name:'Lickilicky',form:null},
  {id:464,name:'Rhyperior',form:null},
  {id:465,name:'Tangrowth',form:null},
  {id:466,name:'Electivire',form:null},
  {id:467,name:'Magmortar',form:null},
  {id:468,name:'Togekiss',form:null},
  {id:469,name:'Yanmega',form:null},
  {id:470,name:'Leafeon',form:null},
  {id:471,name:'Glaceon',form:null},
  {id:472,name:'Gliscor',form:null},
  {id:473,name:'Mamoswine',form:null},
  {id:474,name:'Porygon-Z',form:null},
  {id:475,name:'Gallade',form:null},
  {id:476,name:'Probopass',form:null},
  {id:477,name:'Dusknoir',form:null},
  {id:478,name:'Froslass',form:null},
  {id:479,name:'Rotom',form:null},
  {id:480,name:'Uxie',form:null},
  {id:481,name:'Mesprit',form:null},
  {id:482,name:'Azelf',form:null},
  {id:483,name:'Dialga',form:null},
  {id:484,name:'Palkia',form:null},
  {id:485,name:'Heatran',form:null},
  {id:486,name:'Regigigas',form:null},
  {id:487,name:'Giratina',form:null},
  {id:488,name:'Cresselia',form:null},
  {id:489,name:'Phione',form:null},
  {id:490,name:'Manaphy',form:null},
  {id:491,name:'Darkrai',form:null},
  {id:492,name:'Shaymin',form:null},
  {id:493,name:'Arceus',form:null},

  // Gen 5
  {id:494,name:'Victini',form:null},
  {id:495,name:'Snivy',form:null},
  {id:496,name:'Servine',form:null},
  {id:497,name:'Serperior',form:null},
  {id:498,name:'Tepig',form:null},
  {id:499,name:'Pignite',form:null},
  {id:500,name:'Emboar',form:null},
  {id:501,name:'Oshawott',form:null},
  {id:502,name:'Dewott',form:null},
  {id:503,name:'Samurott',form:null},
  {id:504,name:'Patrat',form:null},
  {id:505,name:'Watchog',form:null},
  {id:506,name:'Lillipup',form:null},
  {id:507,name:'Herdier',form:null},
  {id:508,name:'Stoutland',form:null},
  {id:509,name:'Purrloin',form:null},
  {id:510,name:'Liepard',form:null},
  {id:511,name:'Pansage',form:null},
  {id:512,name:'Simisage',form:null},
  {id:513,name:'Pansear',form:null},
  {id:514,name:'Simisear',form:null},
  {id:515,name:'Panpour',form:null},
  {id:516,name:'Simipour',form:null},
  {id:517,name:'Munna',form:null},
  {id:518,name:'Musharna',form:null},
  {id:519,name:'Pidove',form:null},
  {id:520,name:'Tranquill',form:null},
  {id:521,name:'Unfezant',form:null},
  {id:522,name:'Blitzle',form:null},
  {id:523,name:'Zebstrika',form:null},
  {id:524,name:'Roggenrola',form:null},
  {id:525,name:'Boldore',form:null},
  {id:526,name:'Gigalith',form:null},
  {id:527,name:'Woobat',form:null},
  {id:528,name:'Swoobat',form:null},
  {id:529,name:'Drilbur',form:null},
  {id:530,name:'Excadrill',form:null},
  {id:531,name:'Audino',form:null},
  {id:532,name:'Timburr',form:null},
  {id:533,name:'Gurdurr',form:null},
  {id:534,name:'Conkeldurr',form:null},
  {id:535,name:'Tympole',form:null},
  {id:536,name:'Palpitoad',form:null},
  {id:537,name:'Seismitoad',form:null},
  {id:538,name:'Throh',form:null},
  {id:539,name:'Sawk',form:null},
  {id:540,name:'Sewaddle',form:null},
  {id:541,name:'Swadloon',form:null},
  {id:542,name:'Leavanny',form:null},
  {id:543,name:'Venipede',form:null},
  {id:544,name:'Whirlipede',form:null},
  {id:545,name:'Scolipede',form:null},
  {id:546,name:'Cottonee',form:null},
  {id:547,name:'Whimsicott',form:null},
  {id:548,name:'Petilil',form:null},
  {id:549,name:'Lilligant',form:null},
  {id:550,name:'Basculin',form:null},
  {id:551,name:'Sandile',form:null},
  {id:552,name:'Krokorok',form:null},
  {id:553,name:'Krookodile',form:null},
  {id:554,name:'Darumaka',form:null},
  {id:555,name:'Darmanitan',form:null},
  {id:556,name:'Maractus',form:null},
  {id:557,name:'Dwebble',form:null},
  {id:558,name:'Crustle',form:null},
  {id:559,name:'Scraggy',form:null},
  {id:560,name:'Scrafty',form:null},
  {id:561,name:'Sigilyph',form:null},
  {id:562,name:'Yamask',form:null},
  {id:563,name:'Cofagrigus',form:null},
  {id:564,name:'Tirtouga',form:null},
  {id:565,name:'Carracosta',form:null},
  {id:566,name:'Archen',form:null},
  {id:567,name:'Archeops',form:null},
  {id:568,name:'Trubbish',form:null},
  {id:569,name:'Garbodor',form:null},
  {id:570,name:'Zorua',form:null},
  {id:571,name:'Zoroark',form:null},
  {id:572,name:'Minccino',form:null},
  {id:573,name:'Cinccino',form:null},
  {id:574,name:'Gothita',form:null},
  {id:575,name:'Gothorita',form:null},
  {id:576,name:'Gothitelle',form:null},
  {id:577,name:'Solosis',form:null},
  {id:578,name:'Duosion',form:null},
  {id:579,name:'Reuniclus',form:null},
  {id:580,name:'Ducklett',form:null},
  {id:581,name:'Swanna',form:null},
  {id:582,name:'Vanillite',form:null},
  {id:583,name:'Vanillish',form:null},
  {id:584,name:'Vanilluxe',form:null},
  {id:585,name:'Deerling',form:null},
  {id:586,name:'Sawsbuck',form:null},
  {id:587,name:'Emolga',form:null},
  {id:588,name:'Karrablast',form:null},
  {id:589,name:'Escavalier',form:null},
  {id:590,name:'Foongus',form:null},
  {id:591,name:'Amoonguss',form:null},
  {id:592,name:'Frillish',form:null},
  {id:593,name:'Jellicent',form:null},
  {id:594,name:'Alomomola',form:null},
  {id:595,name:'Joltik',form:null},
  {id:596,name:'Galvantula',form:null},
  {id:597,name:'Ferroseed',form:null},
  {id:598,name:'Ferrothorn',form:null},
  {id:599,name:'Klink',form:null},
  {id:600,name:'Klang',form:null},
  {id:601,name:'Klinklang',form:null},
  {id:602,name:'Tynamo',form:null},
  {id:603,name:'Eelektrik',form:null},
  {id:604,name:'Eelektross',form:null},
  {id:605,name:'Elgyem',form:null},
  {id:606,name:'Beheeyem',form:null},
  {id:607,name:'Litwick',form:null},
  {id:608,name:'Lampent',form:null},
  {id:609,name:'Chandelure',form:null},
  {id:610,name:'Axew',form:null},
  {id:611,name:'Fraxure',form:null},
  {id:612,name:'Haxorus',form:null},
  {id:613,name:'Cubchoo',form:null},
  {id:614,name:'Beartic',form:null},
  {id:615,name:'Cryogonal',form:null},
  {id:616,name:'Shelmet',form:null},
  {id:617,name:'Accelgor',form:null},
  {id:618,name:'Stunfisk',form:null},
  {id:619,name:'Mienfoo',form:null},
  {id:620,name:'Mienshao',form:null},
  {id:621,name:'Druddigon',form:null},
  {id:622,name:'Golett',form:null},
  {id:623,name:'Golurk',form:null},
  {id:624,name:'Pawniard',form:null},
  {id:625,name:'Bisharp',form:null},
  {id:626,name:'Bouffalant',form:null},
  {id:627,name:'Rufflet',form:null},
  {id:628,name:'Braviary',form:null},
  {id:629,name:'Vullaby',form:null},
  {id:630,name:'Mandibuzz',form:null},
  {id:631,name:'Heatmor',form:null},
  {id:632,name:'Durant',form:null},
  {id:633,name:'Deino',form:null},
  {id:634,name:'Zweilous',form:null},
  {id:635,name:'Hydreigon',form:null},
  {id:636,name:'Larvesta',form:null},
  {id:637,name:'Volcarona',form:null},
  {id:638,name:'Cobalion',form:null},
  {id:639,name:'Terrakion',form:null},
  {id:640,name:'Virizion',form:null},
  {id:641,name:'Tornadus',form:null},
  {id:642,name:'Thundurus',form:null},
  {id:643,name:'Reshiram',form:null},
  {id:644,name:'Zekrom',form:null},
  {id:645,name:'Landorus',form:null},
  {id:646,name:'Kyurem',form:null},
  {id:647,name:'Keldeo',form:null},
  {id:648,name:'Meloetta',form:null},
  {id:649,name:'Genesect',form:null},

  // Gen 6
  {id:650,name:'Chespin',form:null},
  {id:651,name:'Quilladin',form:null},
  {id:652,name:'Chesnaught',form:null},
  {id:653,name:'Fennekin',form:null},
  {id:654,name:'Braixen',form:null},
  {id:655,name:'Delphox',form:null},
  {id:656,name:'Froakie',form:null},
  {id:657,name:'Frogadier',form:null},
  {id:658,name:'Greninja',form:null},
  {id:659,name:'Bunnelby',form:null},
  {id:660,name:'Diggersby',form:null},
  {id:661,name:'Fletchling',form:null},
  {id:662,name:'Fletchinder',form:null},
  {id:663,name:'Talonflame',form:null},
  {id:664,name:'Scatterbug',form:null},
  {id:665,name:'Spewpa',form:null},
  {id:666,name:'Vivillon',form:null},
  {id:667,name:'Litleo',form:null},
  {id:668,name:'Pyroar',form:null},
  {id:669,name:'Flabébé',form:null},
  {id:670,name:'Floette',form:null},
  {id:671,name:'Florges',form:null},
  {id:672,name:'Skiddo',form:null},
  {id:673,name:'Gogoat',form:null},
  {id:674,name:'Pancham',form:null},
  {id:675,name:'Pangoro',form:null},
  {id:676,name:'Furfrou',form:null},
  {id:677,name:'Espurr',form:null},
  {id:678,name:'Meowstic',form:null},
  {id:679,name:'Honedge',form:null},
  {id:680,name:'Doublade',form:null},
  {id:681,name:'Aegislash',form:null},
  {id:682,name:'Spritzee',form:null},
  {id:683,name:'Aromatisse',form:null},
  {id:684,name:'Swirlix',form:null},
  {id:685,name:'Slurpuff',form:null},
  {id:686,name:'Inkay',form:null},
  {id:687,name:'Malamar',form:null},
  {id:688,name:'Binacle',form:null},
  {id:689,name:'Barbaracle',form:null},
  {id:690,name:'Skrelp',form:null},
  {id:691,name:'Dragalge',form:null},
  {id:692,name:'Clauncher',form:null},
  {id:693,name:'Clawitzer',form:null},
  {id:694,name:'Helioptile',form:null},
  {id:695,name:'Heliolisk',form:null},
  {id:696,name:'Tyrunt',form:null},
  {id:697,name:'Tyrantrum',form:null},
  {id:698,name:'Amaura',form:null},
  {id:699,name:'Aurorus',form:null},
  {id:700,name:'Sylveon',form:null},
  {id:701,name:'Hawlucha',form:null},
  {id:702,name:'Dedenne',form:null},
  {id:703,name:'Carbink',form:null},
  {id:704,name:'Goomy',form:null},
  {id:705,name:'Sliggoo',form:null},
  {id:706,name:'Goodra',form:null},
  {id:707,name:'Klefki',form:null},
  {id:708,name:'Phantump',form:null},
  {id:709,name:'Trevenant',form:null},
  {id:710,name:'Pumpkaboo',form:null},
  {id:711,name:'Gourgeist',form:null},
  {id:712,name:'Bergmite',form:null},
  {id:713,name:'Avalugg',form:null},
  {id:714,name:'Noibat',form:null},
  {id:715,name:'Noivern',form:null},
  {id:716,name:'Xerneas',form:null},
  {id:717,name:'Yveltal',form:null},
  {id:718,name:'Zygarde',form:null},
  {id:719,name:'Diancie',form:null},
  {id:720,name:'Hoopa',form:null},
  {id:721,name:'Volcanion',form:null},

  // Gen 7
  {id:722,name:'Rowlet',form:null},
  {id:723,name:'Dartrix',form:null},
  {id:724,name:'Decidueye',form:null},
  {id:725,name:'Litten',form:null},
  {id:726,name:'Torracat',form:null},
  {id:727,name:'Incineroar',form:null},
  {id:728,name:'Popplio',form:null},
  {id:729,name:'Brionne',form:null},
  {id:730,name:'Primarina',form:null},
  {id:731,name:'Pikipek',form:null},
  {id:732,name:'Trumbeak',form:null},
  {id:733,name:'Toucannon',form:null},
  {id:734,name:'Yungoos',form:null},
  {id:735,name:'Gumshoos',form:null},
  {id:736,name:'Grubbin',form:null},
  {id:737,name:'Charjabug',form:null},
  {id:738,name:'Vikavolt',form:null},
  {id:739,name:'Crabrawler',form:null},
  {id:740,name:'Crabominable',form:null},
  {id:741,name:'Oricorio',form:null},
  {id:742,name:'Cutiefly',form:null},
  {id:743,name:'Ribombee',form:null},
  {id:744,name:'Rockruff',form:null},
  {id:745,name:'Lycanroc',form:null},
  {id:746,name:'Wishiwashi',form:null},
  {id:747,name:'Mareanie',form:null},
  {id:748,name:'Toxapex',form:null},
  {id:749,name:'Mudbray',form:null},
  {id:750,name:'Mudsdale',form:null},
  {id:751,name:'Dewpider',form:null},
  {id:752,name:'Araquanid',form:null},
  {id:753,name:'Fomantis',form:null},
  {id:754,name:'Lurantis',form:null},
  {id:755,name:'Morelull',form:null},
  {id:756,name:'Shiinotic',form:null},
  {id:757,name:'Salandit',form:null},
  {id:758,name:'Salazzle',form:null},
  {id:759,name:'Stufful',form:null},
  {id:760,name:'Bewear',form:null},
  {id:761,name:'Bounsweet',form:null},
  {id:762,name:'Steenee',form:null},
  {id:763,name:'Tsareena',form:null},
  {id:764,name:'Comfey',form:null},
  {id:765,name:'Oranguru',form:null},
  {id:766,name:'Passimian',form:null},
  {id:767,name:'Wimpod',form:null},
  {id:768,name:'Golisopod',form:null},
  {id:769,name:'Sandygast',form:null},
  {id:770,name:'Palossand',form:null},
  {id:771,name:'Pyukumuku',form:null},
  {id:772,name:'Type: Null',form:null},
  {id:773,name:'Silvally',form:null},
  {id:774,name:'Minior',form:null},
  {id:775,name:'Komala',form:null},
  {id:776,name:'Turtonator',form:null},
  {id:777,name:'Togedemaru',form:null},
  {id:778,name:'Mimikyu',form:null},
  {id:779,name:'Bruxish',form:null},
  {id:780,name:'Drampa',form:null},
  {id:781,name:'Dhelmise',form:null},
  {id:782,name:'Jangmo-o',form:null},
  {id:783,name:'Hakamo-o',form:null},
  {id:784,name:'Kommo-o',form:null},
  {id:785,name:'Tapu Koko',form:null},
  {id:786,name:'Tapu Lele',form:null},
  {id:787,name:'Tapu Bulu',form:null},
  {id:788,name:'Tapu Fini',form:null},
  {id:789,name:'Cosmog',form:null},
  {id:790,name:'Cosmoem',form:null},
  {id:791,name:'Solgaleo',form:null},
  {id:792,name:'Lunala',form:null},
  {id:793,name:'Nihilego',form:null},
  {id:794,name:'Buzzwole',form:null},
  {id:795,name:'Pheromosa',form:null},
  {id:796,name:'Xurkitree',form:null},
  {id:797,name:'Celesteela',form:null},
  {id:798,name:'Kartana',form:null},
  {id:799,name:'Guzzlord',form:null},
  {id:800,name:'Necrozma',form:null},
  {id:801,name:'Magearna',form:null},
  {id:802,name:'Marshadow',form:null},
  {id:803,name:'Poipole',form:null},
  {id:804,name:'Naganadel',form:null},
  {id:805,name:'Stakataka',form:null},
  {id:806,name:'Blacephalon',form:null},
  {id:807,name:'Zeraora',form:null},
  {id:808,name:'Meltan',form:null},
  {id:809,name:'Melmetal',form:null},

  // Gen 8
  {id:810,name:'Grookey',form:null},
  {id:811,name:'Thwackey',form:null},
  {id:812,name:'Rillaboom',form:null},
  {id:813,name:'Scorbunny',form:null},
  {id:814,name:'Raboot',form:null},
  {id:815,name:'Cinderace',form:null},
  {id:816,name:'Sobble',form:null},
  {id:817,name:'Drizzile',form:null},
  {id:818,name:'Inteleon',form:null},
  {id:819,name:'Skwovet',form:null},
  {id:820,name:'Greedent',form:null},
  {id:821,name:'Rookidee',form:null},
  {id:822,name:'Corvisquire',form:null},
  {id:823,name:'Corviknight',form:null},
  {id:824,name:'Blipbug',form:null},
  {id:825,name:'Dottler',form:null},
  {id:826,name:'Orbeetle',form:null},
  {id:827,name:'Nickit',form:null},
  {id:828,name:'Thievul',form:null},
  {id:829,name:'Gossifleur',form:null},
  {id:830,name:'Eldegoss',form:null},
  {id:831,name:'Wooloo',form:null},
  {id:832,name:'Dubwool',form:null},
  {id:833,name:'Chewtle',form:null},
  {id:834,name:'Drednaw',form:null},
  {id:835,name:'Yamper',form:null},
  {id:836,name:'Boltund',form:null},
  {id:837,name:'Rolycoly',form:null},
  {id:838,name:'Carkol',form:null},
  {id:839,name:'Coalossal',form:null},
  {id:840,name:'Applin',form:null},
  {id:841,name:'Flapple',form:null},
  {id:842,name:'Appletun',form:null},
  {id:843,name:'Silicobra',form:null},
  {id:844,name:'Sandaconda',form:null},
  {id:845,name:'Cramorant',form:null},
  {id:846,name:'Arrokuda',form:null},
  {id:847,name:'Barraskewda',form:null},
  {id:848,name:'Toxel',form:null},
  {id:849,name:'Toxtricity',form:null},
  {id:850,name:'Sizzlipede',form:null},
  {id:851,name:'Centiskorch',form:null},
  {id:852,name:'Clobbopus',form:null},
  {id:853,name:'Grapploct',form:null},
  {id:854,name:'Sinistea',form:null},
  {id:855,name:'Polteageist',form:null},
  {id:856,name:'Hatenna',form:null},
  {id:857,name:'Hattrem',form:null},
  {id:858,name:'Hatterene',form:null},
  {id:859,name:'Impidimp',form:null},
  {id:860,name:'Morgrem',form:null},
  {id:861,name:'Grimmsnarl',form:null},
  {id:862,name:'Obstagoon',form:null},
  {id:863,name:'Perrserker',form:null},
  {id:864,name:'Cursola',form:null},
  {id:865,name:'Sirfetch\'d',form:null},
  {id:866,name:'Mr. Rime',form:null},
  {id:867,name:'Runerigus',form:null},
  {id:868,name:'Milcery',form:null},
  {id:869,name:'Alcremie',form:null},
  {id:870,name:'Falinks',form:null},
  {id:871,name:'Pincurchin',form:null},
  {id:872,name:'Snom',form:null},
  {id:873,name:'Frosmoth',form:null},
  {id:874,name:'Stonjourner',form:null},
  {id:875,name:'Eiscue',form:null},
  {id:876,name:'Indeedee',form:null},
  {id:877,name:'Morpeko',form:null},
  {id:878,name:'Cufant',form:null},
  {id:879,name:'Copperajah',form:null},
  {id:880,name:'Dracozolt',form:null},
  {id:881,name:'Arctozolt',form:null},
  {id:882,name:'Dracovish',form:null},
  {id:883,name:'Arctovish',form:null},
  {id:884,name:'Duraludon',form:null},
  {id:885,name:'Dreepy',form:null},
  {id:886,name:'Drakloak',form:null},
  {id:887,name:'Dragapult',form:null},
  {id:888,name:'Zacian',form:null},
  {id:889,name:'Zamazenta',form:null},
  {id:890,name:'Eternatus',form:null},
  {id:891,name:'Kubfu',form:null},
  {id:892,name:'Urshifu',form:null},
  {id:893,name:'Zarude',form:null},
  {id:894,name:'Regieleki',form:null},
  {id:895,name:'Regidrago',form:null},
  {id:896,name:'Glastrier',form:null},
  {id:897,name:'Spectrier',form:null},
  {id:898,name:'Calyrex',form:null},
  {id:899,name:'Wyrdeer',form:null},
  {id:900,name:'Kleavor',form:null},
  {id:901,name:'Ursaluna',form:null},
  {id:902,name:'Basculegion',form:null},
  {id:903,name:'Sneasler',form:null},
  {id:904,name:'Overqwil',form:null},
  {id:905,name:'Enamorus',form:null},

  // Gen 9
  {id:906,name:'Sprigatito',form:null},
  {id:907,name:'Floragato',form:null},
  {id:908,name:'Meowscarada',form:null},
  {id:909,name:'Fuecoco',form:null},
  {id:910,name:'Crocalor',form:null},
  {id:911,name:'Skeledirge',form:null},
  {id:912,name:'Quaxly',form:null},
  {id:913,name:'Quaxwell',form:null},
  {id:914,name:'Quaquaval',form:null},
  {id:915,name:'Lechonk',form:null},
  {id:916,name:'Oinkologne',form:null},
  {id:917,name:'Tarountula',form:null},
  {id:918,name:'Spidops',form:null},
  {id:919,name:'Nymble',form:null},
  {id:920,name:'Lokix',form:null},
  {id:921,name:'Pawmi',form:null},
  {id:922,name:'Pawmo',form:null},
  {id:923,name:'Pawmot',form:null},
  {id:924,name:'Tandemaus',form:null},
  {id:925,name:'Maushold',form:null},
  {id:926,name:'Fidough',form:null},
  {id:927,name:'Dachsbun',form:null},
  {id:928,name:'Smoliv',form:null},
  {id:929,name:'Dolliv',form:null},
  {id:930,name:'Arboliva',form:null},
  {id:931,name:'Squawkabilly',form:null},
  {id:932,name:'Nacli',form:null},
  {id:933,name:'Naclstack',form:null},
  {id:934,name:'Garganacl',form:null},
  {id:935,name:'Charcadet',form:null},
  {id:936,name:'Armarouge',form:null},
  {id:937,name:'Ceruledge',form:null},
  {id:938,name:'Tadbulb',form:null},
  {id:939,name:'Bellibolt',form:null},
  {id:940,name:'Wattrel',form:null},
  {id:941,name:'Kilowattrel',form:null},
  {id:942,name:'Maschiff',form:null},
  {id:943,name:'Mabosstiff',form:null},
  {id:944,name:'Shroodle',form:null},
  {id:945,name:'Grafaiai',form:null},
  {id:946,name:'Bramblin',form:null},
  {id:947,name:'Brambleghast',form:null},
  {id:948,name:'Toedscool',form:null},
  {id:949,name:'Toedscruel',form:null},
  {id:950,name:'Klawf',form:null},
  {id:951,name:'Capsakid',form:null},
  {id:952,name:'Scovillain',form:null},
  {id:953,name:'Rellor',form:null},
  {id:954,name:'Rabsca',form:null},
  {id:955,name:'Flittle',form:null},
  {id:956,name:'Espathra',form:null},
  {id:957,name:'Tinkatink',form:null},
  {id:958,name:'Tinkatuff',form:null},
  {id:959,name:'Tinkaton',form:null},
  {id:960,name:'Wiglett',form:null},
  {id:961,name:'Wugtrio',form:null},
  {id:962,name:'Bombirdier',form:null},
  {id:963,name:'Finizen',form:null},
  {id:964,name:'Palafin',form:null},
  {id:965,name:'Varoom',form:null},
  {id:966,name:'Revavroom',form:null},
  {id:967,name:'Cyclizar',form:null},
  {id:968,name:'Orthworm',form:null},
  {id:969,name:'Glimmet',form:null},
  {id:970,name:'Glimmora',form:null},
  {id:971,name:'Greavard',form:null},
  {id:972,name:'Houndstone',form:null},
  {id:973,name:'Flamigo',form:null},
  {id:974,name:'Cetoddle',form:null},
  {id:975,name:'Cetitan',form:null},
  {id:976,name:'Veluza',form:null},
  {id:977,name:'Dondozo',form:null},
  {id:978,name:'Tatsugiri',form:null},
  {id:979,name:'Annihilape',form:null},
  {id:980,name:'Clodsire',form:null},
  {id:981,name:'Farigiraf',form:null},
  {id:982,name:'Dudunsparce',form:null},
  {id:983,name:'Kingambit',form:null},
  {id:984,name:'Great Tusk',form:null},
  {id:985,name:'Scream Tail',form:null},
  {id:986,name:'Brute Bonnet',form:null},
  {id:987,name:'Flutter Mane',form:null},
  {id:988,name:'Slither Wing',form:null},
  {id:989,name:'Sandy Shocks',form:null},
  {id:990,name:'Iron Treads',form:null},
  {id:991,name:'Iron Bundle',form:null},
  {id:992,name:'Iron Hands',form:null},
  {id:993,name:'Iron Jugulis',form:null},
  {id:994,name:'Iron Moth',form:null},
  {id:995,name:'Iron Thorns',form:null},
  {id:996,name:'Frigibax',form:null},
  {id:997,name:'Arctibax',form:null},
  {id:998,name:'Baxcalibur',form:null},
  {id:999,name:'Gimmighoul',form:null},
  {id:1000,name:'Gholdengo',form:null},
  {id:1001,name:'Wo-Chien',form:null},
  {id:1002,name:'Chien-Pao',form:null},
  {id:1003,name:'Ting-Lu',form:null},
  {id:1004,name:'Chi-Yu',form:null},
  {id:1005,name:'Roaring Moon',form:null},
  {id:1006,name:'Iron Valiant',form:null},
  {id:1007,name:'Koraidon',form:null},
  {id:1008,name:'Miraidon',form:null},
  {id:1009,name:'Walking Wake',form:null},
  {id:1010,name:'Iron Leaves',form:null},
  {id:1011,name:'Dipplin',form:null},
  {id:1012,name:'Poltchageist',form:null},
  {id:1013,name:'Sinistcha',form:null},
  {id:1014,name:'Okidogi',form:null},
  {id:1015,name:'Munkidori',form:null},
  {id:1016,name:'Fezandipiti',form:null},
  {id:1017,name:'Ogerpon',form:null},
  {id:1018,name:'Archaludon',form:null},
  {id:1019,name:'Hydrapple',form:null},
  {id:1020,name:'Gouging Fire',form:null},
  {id:1021,name:'Raging Bolt',form:null},
  {id:1022,name:'Iron Boulder',form:null},
  {id:1023,name:'Iron Crown',form:null},
  {id:1024,name:'Terapagos',form:null},
  {id:1025,name:'Pecharunt',form:null},

  // Regional forms
  {id:27,name:'Sandshrew (Alola)',form:'alola',baseId:27},
  {id:28,name:'Sandslash (Alola)',form:'alola',baseId:28},
  {id:37,name:'Vulpix (Alola)',form:'alola',baseId:37},
  {id:38,name:'Ninetales (Alola)',form:'alola',baseId:38},
  {id:26,name:'Raichu (Alola)',form:'alola',baseId:26},
  {id:52,name:'Meowth (Alola)',form:'alola',baseId:52},
  {id:53,name:'Persian (Alola)',form:'alola',baseId:53},
  {id:74,name:'Geodude (Alola)',form:'alola',baseId:74},
  {id:75,name:'Graveler (Alola)',form:'alola',baseId:75},
  {id:76,name:'Golem (Alola)',form:'alola',baseId:76},
  {id:88,name:'Grimer (Alola)',form:'alola',baseId:88},
  {id:89,name:'Muk (Alola)',form:'alola',baseId:89},
  {id:103,name:'Exeggutor (Alola)',form:'alola',baseId:103},
  {id:105,name:'Marowak (Alola)',form:'alola',baseId:105},
  {id:50,name:'Diglett (Alola)',form:'alola',baseId:50},
  {id:51,name:'Dugtrio (Alola)',form:'alola',baseId:51},
  {id:77,name:'Ponyta (Galar)',form:'galar',baseId:77},
  {id:78,name:'Rapidash (Galar)',form:'galar',baseId:78},
  {id:79,name:'Slowpoke (Galar)',form:'galar',baseId:79},
  {id:80,name:'Slowbro (Galar)',form:'galar',baseId:80},
  {id:52,name:'Meowth (Galar)',form:'galar',baseId:52},
  {id:110,name:'Weezing (Galar)',form:'galar',baseId:110},
  {id:122,name:'Mr. Mime (Galar)',form:'galar',baseId:122},
  {id:199,name:'Slowking (Galar)',form:'galar',baseId:199},
  {id:222,name:'Corsola (Galar)',form:'galar',baseId:222},
  {id:554,name:'Darumaka (Galar)',form:'galar',baseId:554},
  {id:555,name:'Darmanitan (Galar)',form:'galar',baseId:555},
  {id:562,name:'Yamask (Galar)',form:'galar',baseId:562},
  {id:618,name:'Stunfisk (Galar)',form:'galar',baseId:618},
  {id:58,name:'Growlithe (Hisui)',form:'hisui',baseId:58},
  {id:59,name:'Arcanine (Hisui)',form:'hisui',baseId:59},
  {id:157,name:'Typhlosion (Hisui)',form:'hisui',baseId:157},
  {id:100,name:'Voltorb (Hisui)',form:'hisui',baseId:100},
  {id:101,name:'Electrode (Hisui)',form:'hisui',baseId:101},
  {id:503,name:'Samurott (Hisui)',form:'hisui',baseId:503},
  {id:549,name:'Lilligant (Hisui)',form:'hisui',baseId:549},
  {id:570,name:'Zorua (Hisui)',form:'hisui',baseId:570},
  {id:571,name:'Zoroark (Hisui)',form:'hisui',baseId:571},
  {id:628,name:'Braviary (Hisui)',form:'hisui',baseId:628},
  {id:713,name:'Avalugg (Hisui)',form:'hisui',baseId:713},
  {id:724,name:'Decidueye (Hisui)',form:'hisui',baseId:724},
  {id:128,name:'Tauros (Paldea)',form:'paldea',baseId:128},
  {id:194,name:'Wooper (Paldea)',form:'paldea',baseId:194},

  // Multi-form Pokemon
  {id:201,name:'Unown (A)',form:'a',baseId:201},
  {id:201,name:'Unown (B)',form:'b',baseId:201},
  {id:201,name:'Unown (C)',form:'c',baseId:201},
  {id:201,name:'Unown (D)',form:'d',baseId:201},
  {id:201,name:'Unown (E)',form:'e',baseId:201},
  {id:201,name:'Unown (F)',form:'f',baseId:201},
  {id:201,name:'Unown (G)',form:'g',baseId:201},
  {id:201,name:'Unown (H)',form:'h',baseId:201},
  {id:201,name:'Unown (I)',form:'i',baseId:201},
  {id:201,name:'Unown (J)',form:'j',baseId:201},
  {id:201,name:'Unown (K)',form:'k',baseId:201},
  {id:201,name:'Unown (L)',form:'l',baseId:201},
  {id:201,name:'Unown (M)',form:'m',baseId:201},
  {id:201,name:'Unown (N)',form:'n',baseId:201},
  {id:201,name:'Unown (O)',form:'o',baseId:201},
  {id:201,name:'Unown (P)',form:'p',baseId:201},
  {id:201,name:'Unown (Q)',form:'q',baseId:201},
  {id:201,name:'Unown (R)',form:'r',baseId:201},
  {id:201,name:'Unown (S)',form:'s',baseId:201},
  {id:201,name:'Unown (T)',form:'t',baseId:201},
  {id:201,name:'Unown (U)',form:'u',baseId:201},
  {id:201,name:'Unown (V)',form:'v',baseId:201},
  {id:201,name:'Unown (W)',form:'w',baseId:201},
  {id:201,name:'Unown (X)',form:'x',baseId:201},
  {id:201,name:'Unown (Y)',form:'y',baseId:201},
  {id:201,name:'Unown (Z)',form:'z',baseId:201},
  {id:201,name:'Unown (!)',form:'exclamation',baseId:201},
  {id:201,name:'Unown (?)',form:'question',baseId:201},
  {id:351,name:'Castform (Rainy)',form:'rainy',baseId:351},
  {id:351,name:'Castform (Sunny)',form:'sunny',baseId:351},
  {id:351,name:'Castform (Snowy)',form:'snowy',baseId:351},
  {id:421,name:'Cherrim (Sunshine)',form:'sunshine',baseId:421},
  {id:412,name:'Burmy (Sandy)',form:'sandy',baseId:412},
  {id:412,name:'Burmy (Trash)',form:'trash',baseId:412},
  {id:413,name:'Wormadam (Sandy)',form:'sandy',baseId:413},
  {id:413,name:'Wormadam (Trash)',form:'trash',baseId:413},
  {id:422,name:'Shellos (East)',form:'east',baseId:422},
  {id:423,name:'Gastrodon (East)',form:'east',baseId:423},
  {id:479,name:'Rotom (Heat)',form:'heat',baseId:479},
  {id:479,name:'Rotom (Wash)',form:'wash',baseId:479},
  {id:479,name:'Rotom (Frost)',form:'frost',baseId:479},
  {id:479,name:'Rotom (Fan)',form:'fan',baseId:479},
  {id:479,name:'Rotom (Mow)',form:'mow',baseId:479},
  {id:487,name:'Giratina (Origin)',form:'origin',baseId:487},
  {id:492,name:'Shaymin (Sky)',form:'sky',baseId:492},
  {id:493,name:'Arceus (Bug)',form:'bug',baseId:493},
  {id:493,name:'Arceus (Dark)',form:'dark',baseId:493},
  {id:493,name:'Arceus (Dragon)',form:'dragon',baseId:493},
  {id:493,name:'Arceus (Electric)',form:'electric',baseId:493},
  {id:493,name:'Arceus (Fairy)',form:'fairy',baseId:493},
  {id:493,name:'Arceus (Fighting)',form:'fighting',baseId:493},
  {id:493,name:'Arceus (Fire)',form:'fire',baseId:493},
  {id:493,name:'Arceus (Flying)',form:'flying',baseId:493},
  {id:493,name:'Arceus (Ghost)',form:'ghost',baseId:493},
  {id:493,name:'Arceus (Grass)',form:'grass',baseId:493},
  {id:493,name:'Arceus (Ground)',form:'ground',baseId:493},
  {id:493,name:'Arceus (Ice)',form:'ice',baseId:493},
  {id:493,name:'Arceus (Poison)',form:'poison',baseId:493},
  {id:493,name:'Arceus (Psychic)',form:'psychic',baseId:493},
  {id:493,name:'Arceus (Rock)',form:'rock',baseId:493},
  {id:493,name:'Arceus (Steel)',form:'steel',baseId:493},
  {id:493,name:'Arceus (Water)',form:'water',baseId:493},
  {id:550,name:'Basculin (Red)',form:'red',baseId:550},
  {id:550,name:'Basculin (Blue)',form:'blue',baseId:550},
  {id:550,name:'Basculin (White-Striped)',form:'white',baseId:550},
  {id:555,name:'Darmanitan (Zen)',form:'zen',baseId:555},
  {id:641,name:'Tornadus (Therian)',form:'therian',baseId:641},
  {id:642,name:'Thundurus (Therian)',form:'therian',baseId:642},
  {id:645,name:'Landorus (Therian)',form:'therian',baseId:645},
  {id:646,name:'Kyurem (White)',form:'white',baseId:646},
  {id:646,name:'Kyurem (Black)',form:'black',baseId:646},
  {id:681,name:'Aegislash (Blade)',form:'blade',baseId:681},
  {id:678,name:'Meowstic (Female)',form:'female',baseId:678},
  {id:876,name:'Indeedee (Male)',form:'male',baseId:876},
  {id:876,name:'Indeedee (Female)',form:'female',baseId:876},
  {id:741,name:'Oricorio (Pom-Pom)',form:'pompom',baseId:741},
  {id:741,name:'Oricorio (Pa\'u)',form:'pau',baseId:741},
  {id:741,name:'Oricorio (Sensu)',form:'sensu',baseId:741},
  {id:745,name:'Lycanroc (Midnight)',form:'midnight',baseId:745},
  {id:745,name:'Lycanroc (Dusk)',form:'dusk',baseId:745},
  {id:778,name:'Mimikyu (Busted)',form:'busted',baseId:778},
  {id:800,name:'Necrozma (Dusk Mane)',form:'duskmane',baseId:800},
  {id:800,name:'Necrozma (Dawn Wings)',form:'dawnwings',baseId:800},
  {id:800,name:'Necrozma (Ultra)',form:'ultra',baseId:800},
  {id:801,name:'Magearna (Original)',form:'original',baseId:801},
  {id:849,name:'Toxtricity (Low Key)',form:'lowkey',baseId:849},
  {id:875,name:'Eiscue (Noice)',form:'noice',baseId:875},
  {id:877,name:'Morpeko (Hangry)',form:'hangry',baseId:877},
  {id:892,name:'Urshifu (Rapid Strike)',form:'rapidstrike',baseId:892},
  {id:893,name:'Zarude (Dada)',form:'dada',baseId:893},
  {id:898,name:'Calyrex (Ice)',form:'ice',baseId:898},
  {id:898,name:'Calyrex (Shadow)',form:'shadow',baseId:898},
  {id:902,name:'Basculegion (Male)',form:'male',baseId:902},
  {id:902,name:'Basculegion (Female)',form:'female',baseId:902},
  {id:905,name:'Enamorus (Therian)',form:'therian',baseId:905},
  {id:978,name:'Tatsugiri (Droopy)',form:'droopy',baseId:978},
  {id:978,name:'Tatsugiri (Stretchy)',form:'stretchy',baseId:978},
  {id:1024,name:'Terapagos (Terastal)',form:'terastal',baseId:1024},
  {id:1024,name:'Terapagos (Stellar)',form:'stellar',baseId:1024},

];

module.exports = SPECIES;
